// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type OpenapiAdminAddDomain = {
    domain: string;
    tenant: string;
};

export type OpenapiAdminDeleteDomain = {
    domain: string;
    tenant: string;
};

export type OpenapiAdminDeleteTenant = {
    name: string;
};

export type OpenapiAdminNewTenant = {
    /**
     * First admin user; created and granted the builtin `admin` role.
     */
    admin?: string | null;
    /**
     * First domain of the new tenant; the standard admin policy set is
     * bound to it (`g10-privilege-escalation.md` §4). Without a domain the
     * tenant stays default-deny locked until one is added.
     */
    domain?: string | null;
    name: string;
};

export type OpenapiDbHttpMethod = 'GET' | 'POST' | 'PUT' | 'OPTIONS' | 'DELETE' | 'PATCH' | 'CONNECT' | 'HEAD' | 'TRACE';

export type OpenapiEmailEmailResponse = {
    code: number;
    jwt?: string | null;
    msg: string;
    ok: boolean;
};

export type OpenapiEmailReqRequest = {
    email: string;
    name: string;
};

export type OpenapiIdpDeleteOauth2Client = {
    client_id: string;
};

export type OpenapiIdpNewOauth2Client = {
    client_id: string;
    default_scopes: string;
    grant_types: string;
    redirect_uris: string;
    response_types: string;
    secret: string;
    token_endpoint_auth_method: string;
};

export type OpenapiIdpOAuth2ClientDto = {
    active: boolean;
    created_at: string;
    domain_id: string;
    grant_types: string;
    id: string;
    redirect_uris: string;
    response_types: string;
    scope: string;
    secret_grace_until?: string | null;
    token_endpoint_auth_method: string;
    updated_at: string;
};

export type OpenapiKeyAddkey = {
    domain: string;
    name: string;
};

export type OpenapiKeyDeleteKey = {
    name: string;
};

export type OpenapiKeyKeyEntry = {
    domain: string;
    name: string;
    public: string;
};

export type OpenapiOtpMobileResponse = {
    code: number;
    jwt?: string | null;
    msg: string;
    ok: boolean;
};

export type OpenapiOtpReqRequest = {
    mobile: string;
    name: string;
};

export type OpenapiPasskeyPasskeyRequest = string;

/**
 * Response body for the registration/login challenge.
 */
export type OpenapiPasskeyPasskeyResponse = {
    publicKey: unknown;
    /**
     * Opaque per-flow handle the client must echo back to `verify`
     * (G-20). Replaces the old username-derived cache key.
     */
    token: string;
};

export type OpenapiPasskeyVerifyRequest = {
    cookie?: string | null;
    credential: unknown;
    /**
     * Flow handle from `passkey/request` (G-20): selects the cached
     * challenge. Required — without it no ceremony can be completed.
     */
    token: string;
    username: string;
};

/**
 * Request body for [`delete_policy`] — identifies a policy by its
 * resource template, HTTP method, and role. The domain is always the one
 * resolved from the request `Host` (G-56); a `domain` field present in
 * the body is ignored.
 */
export type OpenapiPolicyDeletePolicy = {
    action?: null | OpenapiDbHttpMethod;
    resource: string;
    role: string;
};

/**
 * Wire-format representation of a [`Policy`] for HTTP responses and request
 * bodies. `resource` is a slash-joined path template (e.g. `"users/{id}"`)
 * rather than the segmented `Vec<String>` stored on the model.
 */
export type OpenapiPolicyPolicyEntry = {
    action?: null | OpenapiDbHttpMethod;
    allowed: boolean;
    domain: string;
    id?: string | null;
    mfa: boolean;
    resource: string;
    role: string;
    source: OpenapiPolicySourceResolver;
    target: OpenapiPolicyTargetResolver;
};

/**
 * How the *source* (the identity acting in the request) is resolved from the
 * authenticated JWT. Used by a [`Policy`] to decide whether the caller itself
 * is the target of the rule.
 *
 * `Nothing` means the policy is identity-independent (it applies to whoever
 * holds the role). `User`, `Domain`, and `Roles` pull the corresponding field
 * from the JWT to be compared against the resolved target.
 */
export type OpenapiPolicySourceResolver = 'Nothing' | 'User' | 'Domain' | 'Role';

/**
 * How the *target* (the resource being accessed) is extracted from the
 * incoming request so it can be compared against the resolved source.
 *
 * - `Nothing`      — no target extraction; matching is purely path-based.
 * - `FromPath`     — capture a named path parameter (e.g. `{user}`) from the
 * request path, matched against the policy's `resource` template.
 * - `FromQuery`    — read the target from a named query-string parameter.
 * - `FromHeader`   — read the target from a request header (case-insensitive
 * lookup).
 */
export type OpenapiPolicyTargetResolver = 'Nothing' | {
    FromPath: {
        pname: string;
    };
} | {
    FromQuery: {
        qname: string;
    };
} | {
    FromHeader: {
        hname: string;
    };
};

export type OpenapiRoleAddRole = {
    /**
     * Privilege level of the new role; must lie in `[0, caller level)`.
     */
    level: number;
    name: string;
};

export type OpenapiRoleDeleteRole = {
    name: string;
};

export type OpenapiRoleRoleEntry = {
    builtin: boolean;
    level: number;
    name: string;
};

export type OpenapiRouterHealthyResponse = {
    ok: boolean;
};

export type OpenapiSocialAddProvider = {
    client_id: string;
    client_secret: string;
    issuer_url: string;
    name: string;
};

export type OpenapiSocialRedeemRequest = {
    code: string;
};

export type OpenapiSocialRemoveProvider = {
    name: string;
};

export type OpenapiSocialSocialProvider = {
    client_id: string;
    client_secret: string;
    id: string;
    issuer_url: string;
    scopes?: Array<string>;
};

export type OpenapiTotpAllTotpRequest = {
    name?: string | null;
};

export type OpenapiTotpEnrollTotpRequest = {
    name: string;
    user?: string | null;
};

export type OpenapiTotpEnrollTotpResponse = {
    domain: string;
    name: string;
    qr: string;
    token: string;
    uri: string;
    user: string;
};

export type OpenapiTotpRemoveTotpRequest = {
    name: string;
    totp: string;
};

export type OpenapiTotpTotpEntry = {
    active: boolean;
    name: string;
};

export type OpenapiTotpVerifyTotpRequest = {
    code: string;
    cookie?: string | null;
    name?: string | null;
    token?: string | null;
    user: string;
};

export type OpenapiUserActivateSelf = {
    active: boolean;
};

export type OpenapiUserActivateUser = {
    active: boolean;
    user: string;
};

export type OpenapiUserAddRole = {
    role: string;
    user: string;
};

export type OpenapiUserAddUser = {
    name: string;
};

export type OpenapiUserDeleteUser = {
    user: string;
};

export type OpenapiUserRemoveRole = {
    role: string;
    user: string;
};

export type OpenapiUserUserRoleRequest = {
    user: string;
};

export type OpenapiUtilsApiProblem = {
    detail?: string | null;
    status: number;
    type: string;
};

export type OpenapiUtilsApiResponse____ = {
    data: unknown;
    ok: boolean;
};

export type OpenapiUtilsApiResponse_String_ = {
    data: string;
    ok: boolean;
};

export type OpenapiUtilsApiResponse_allocVecVec_String__ = {
    data: Array<string>;
    ok: boolean;
};

export type OpenapiUtilsApiResponse_allocVecVec_openapiIdpOAuth2ClientDto__ = {
    data: Array<OpenapiIdpOAuth2ClientDto>;
    ok: boolean;
};

export type OpenapiUtilsApiResponse_allocVecVec_openapiKeyKeyEntry__ = {
    data: Array<OpenapiKeyKeyEntry>;
    ok: boolean;
};

export type OpenapiUtilsApiResponse_allocVecVec_openapiPolicyPolicyEntry__ = {
    data: Array<OpenapiPolicyPolicyEntry>;
    ok: boolean;
};

export type OpenapiUtilsApiResponse_allocVecVec_openapiRoleRoleEntry__ = {
    data: Array<OpenapiRoleRoleEntry>;
    ok: boolean;
};

export type OpenapiUtilsApiResponse_allocVecVec_openapiSocialSocialProvider__ = {
    data: Array<OpenapiSocialSocialProvider>;
    ok: boolean;
};

export type OpenapiUtilsApiResponse_allocVecVec_openapiTotpTotpEntry__ = {
    data: Array<OpenapiTotpTotpEntry>;
    ok: boolean;
};

export type OpenapiAdminAddDomainData = {
    body: OpenapiAdminAddDomain;
    path?: never;
    query?: never;
    url: '/api/v1/admin/domain/create';
};

export type OpenapiAdminAddDomainErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiAdminAddDomainError = OpenapiAdminAddDomainErrors[keyof OpenapiAdminAddDomainErrors];

export type OpenapiAdminAddDomainResponses = {
    /**
     * Domain created successfully
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiAdminAddDomainResponse = OpenapiAdminAddDomainResponses[keyof OpenapiAdminAddDomainResponses];

export type OpenapiAdminDeleteDomainData = {
    body: OpenapiAdminDeleteDomain;
    path?: never;
    query?: never;
    url: '/api/v1/admin/domain/delete';
};

export type OpenapiAdminDeleteDomainErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiAdminDeleteDomainError = OpenapiAdminDeleteDomainErrors[keyof OpenapiAdminDeleteDomainErrors];

export type OpenapiAdminDeleteDomainResponses = {
    /**
     * Domain removed successfully
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiAdminDeleteDomainResponse = OpenapiAdminDeleteDomainResponses[keyof OpenapiAdminDeleteDomainResponses];

export type OpenapiAdminAllDomainsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/domain/list';
};

export type OpenapiAdminAllDomainsErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiAdminAllDomainsError = OpenapiAdminAllDomainsErrors[keyof OpenapiAdminAllDomainsErrors];

export type OpenapiAdminAllDomainsResponses = {
    /**
     * All domain names of the tenant
     */
    200: OpenapiUtilsApiResponse_allocVecVec_String__;
};

export type OpenapiAdminAllDomainsResponse = OpenapiAdminAllDomainsResponses[keyof OpenapiAdminAllDomainsResponses];

export type OpenapiKeyAddKeyData = {
    body: OpenapiKeyAddkey;
    path?: never;
    query?: never;
    url: '/api/v1/admin/key/create';
};

export type OpenapiKeyAddKeyErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiKeyAddKeyError = OpenapiKeyAddKeyErrors[keyof OpenapiKeyAddKeyErrors];

export type OpenapiKeyAddKeyResponses = {
    /**
     * Scope created successfully
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiKeyAddKeyResponse = OpenapiKeyAddKeyResponses[keyof OpenapiKeyAddKeyResponses];

export type OpenapiKeyDeleteKeyData = {
    body: OpenapiKeyDeleteKey;
    path?: never;
    query?: never;
    url: '/api/v1/admin/key/delete';
};

export type OpenapiKeyDeleteKeyErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiKeyDeleteKeyError = OpenapiKeyDeleteKeyErrors[keyof OpenapiKeyDeleteKeyErrors];

export type OpenapiKeyDeleteKeyResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiKeyDeleteKeyResponse = OpenapiKeyDeleteKeyResponses[keyof OpenapiKeyDeleteKeyResponses];

export type OpenapiKeyAllKeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/key/list';
};

export type OpenapiKeyAllKeysErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiKeyAllKeysError = OpenapiKeyAllKeysErrors[keyof OpenapiKeyAllKeysErrors];

export type OpenapiKeyAllKeysResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse_allocVecVec_openapiKeyKeyEntry__;
};

export type OpenapiKeyAllKeysResponse = OpenapiKeyAllKeysResponses[keyof OpenapiKeyAllKeysResponses];

export type OpenapiIdpNewOauth2ClientData = {
    body: OpenapiIdpNewOauth2Client;
    path?: never;
    query?: never;
    url: '/api/v1/admin/oauth2client/create';
};

export type OpenapiIdpNewOauth2ClientErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiIdpNewOauth2ClientError = OpenapiIdpNewOauth2ClientErrors[keyof OpenapiIdpNewOauth2ClientErrors];

export type OpenapiIdpNewOauth2ClientResponses = {
    /**
     * Client created successfully
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiIdpNewOauth2ClientResponse = OpenapiIdpNewOauth2ClientResponses[keyof OpenapiIdpNewOauth2ClientResponses];

export type OpenapiIdpDeleteOauth2ClientData = {
    body: OpenapiIdpDeleteOauth2Client;
    path?: never;
    query?: never;
    url: '/api/v1/admin/oauth2client/delete';
};

export type OpenapiIdpDeleteOauth2ClientErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiIdpDeleteOauth2ClientError = OpenapiIdpDeleteOauth2ClientErrors[keyof OpenapiIdpDeleteOauth2ClientErrors];

export type OpenapiIdpDeleteOauth2ClientResponses = {
    /**
     * Client deactivated
     */
    200: OpenapiUtilsApiResponse_String_;
};

export type OpenapiIdpDeleteOauth2ClientResponse = OpenapiIdpDeleteOauth2ClientResponses[keyof OpenapiIdpDeleteOauth2ClientResponses];

export type OpenapiIdpListOauth2ClientsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/oauth2client/list';
};

export type OpenapiIdpListOauth2ClientsErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiIdpListOauth2ClientsError = OpenapiIdpListOauth2ClientsErrors[keyof OpenapiIdpListOauth2ClientsErrors];

export type OpenapiIdpListOauth2ClientsResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse_allocVecVec_openapiIdpOAuth2ClientDto__;
};

export type OpenapiIdpListOauth2ClientsResponse = OpenapiIdpListOauth2ClientsResponses[keyof OpenapiIdpListOauth2ClientsResponses];

export type OpenapiPolicyAddPolicyData = {
    body: OpenapiPolicyPolicyEntry;
    path?: never;
    query?: never;
    url: '/api/v1/admin/policy/create';
};

export type OpenapiPolicyAddPolicyErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
    /**
     * Level gate refused the role
     */
    403: OpenapiUtilsApiProblem;
};

export type OpenapiPolicyAddPolicyError = OpenapiPolicyAddPolicyErrors[keyof OpenapiPolicyAddPolicyErrors];

export type OpenapiPolicyAddPolicyResponses = {
    /**
     * Policy created successfully
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiPolicyAddPolicyResponse = OpenapiPolicyAddPolicyResponses[keyof OpenapiPolicyAddPolicyResponses];

export type OpenapiPolicyDeletePolicyData = {
    body: OpenapiPolicyDeletePolicy;
    path?: never;
    query?: never;
    url: '/api/v1/admin/policy/delete';
};

export type OpenapiPolicyDeletePolicyErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
    /**
     * Level gate refused the role
     */
    403: OpenapiUtilsApiProblem;
};

export type OpenapiPolicyDeletePolicyError = OpenapiPolicyDeletePolicyErrors[keyof OpenapiPolicyDeletePolicyErrors];

export type OpenapiPolicyDeletePolicyResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiPolicyDeletePolicyResponse = OpenapiPolicyDeletePolicyResponses[keyof OpenapiPolicyDeletePolicyResponses];

export type OpenapiPolicyAllPoliciesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/policy/list';
};

export type OpenapiPolicyAllPoliciesErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiPolicyAllPoliciesError = OpenapiPolicyAllPoliciesErrors[keyof OpenapiPolicyAllPoliciesErrors];

export type OpenapiPolicyAllPoliciesResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse_allocVecVec_openapiPolicyPolicyEntry__;
};

export type OpenapiPolicyAllPoliciesResponse = OpenapiPolicyAllPoliciesResponses[keyof OpenapiPolicyAllPoliciesResponses];

export type OpenapiSocialAddProviderData = {
    body: OpenapiSocialAddProvider;
    path?: never;
    query?: never;
    url: '/api/v1/admin/provider/create';
};

export type OpenapiSocialAddProviderErrors = {
    /**
     * Token exchange failed
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiSocialAddProviderError = OpenapiSocialAddProviderErrors[keyof OpenapiSocialAddProviderErrors];

export type OpenapiSocialAddProviderResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiSocialAddProviderResponse = OpenapiSocialAddProviderResponses[keyof OpenapiSocialAddProviderResponses];

export type OpenapiSocialRemoveProviderData = {
    body: OpenapiSocialRemoveProvider;
    path?: never;
    query?: never;
    url: '/api/v1/admin/provider/delete';
};

export type OpenapiSocialRemoveProviderErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiSocialRemoveProviderError = OpenapiSocialRemoveProviderErrors[keyof OpenapiSocialRemoveProviderErrors];

export type OpenapiSocialRemoveProviderResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiSocialRemoveProviderResponse = OpenapiSocialRemoveProviderResponses[keyof OpenapiSocialRemoveProviderResponses];

export type OpenapiSocialAllProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/provider/list';
};

export type OpenapiSocialAllProvidersErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiSocialAllProvidersError = OpenapiSocialAllProvidersErrors[keyof OpenapiSocialAllProvidersErrors];

export type OpenapiSocialAllProvidersResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse_allocVecVec_openapiSocialSocialProvider__;
};

export type OpenapiSocialAllProvidersResponse = OpenapiSocialAllProvidersResponses[keyof OpenapiSocialAllProvidersResponses];

export type OpenapiRoleAddRoleData = {
    body: OpenapiRoleAddRole;
    path?: never;
    query?: never;
    url: '/api/v1/admin/role/create';
};

export type OpenapiRoleAddRoleErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
    /**
     * Level gate refused the role
     */
    403: OpenapiUtilsApiProblem;
    /**
     * Role name already exists
     */
    409: OpenapiUtilsApiProblem;
};

export type OpenapiRoleAddRoleError = OpenapiRoleAddRoleErrors[keyof OpenapiRoleAddRoleErrors];

export type OpenapiRoleAddRoleResponses = {
    /**
     * Role created successfully
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiRoleAddRoleResponse = OpenapiRoleAddRoleResponses[keyof OpenapiRoleAddRoleResponses];

export type OpenapiRoleDeleteRoleData = {
    body: OpenapiRoleDeleteRole;
    path?: never;
    query?: never;
    url: '/api/v1/admin/role/delete';
};

export type OpenapiRoleDeleteRoleErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
    /**
     * Level gate refused the role
     */
    403: OpenapiUtilsApiProblem;
};

export type OpenapiRoleDeleteRoleError = OpenapiRoleDeleteRoleErrors[keyof OpenapiRoleDeleteRoleErrors];

export type OpenapiRoleDeleteRoleResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiRoleDeleteRoleResponse = OpenapiRoleDeleteRoleResponses[keyof OpenapiRoleDeleteRoleResponses];

export type OpenapiRoleAllRolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/role/list';
};

export type OpenapiRoleAllRolesErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiRoleAllRolesError = OpenapiRoleAllRolesErrors[keyof OpenapiRoleAllRolesErrors];

export type OpenapiRoleAllRolesResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse_allocVecVec_openapiRoleRoleEntry__;
};

export type OpenapiRoleAllRolesResponse = OpenapiRoleAllRolesResponses[keyof OpenapiRoleAllRolesResponses];

export type OpenapiAdminNewTenantData = {
    body: OpenapiAdminNewTenant;
    path?: never;
    query?: never;
    url: '/api/v1/admin/tenant/create';
};

export type OpenapiAdminNewTenantErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiAdminNewTenantError = OpenapiAdminNewTenantErrors[keyof OpenapiAdminNewTenantErrors];

export type OpenapiAdminNewTenantResponses = {
    /**
     * Tenant created successfully
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiAdminNewTenantResponse = OpenapiAdminNewTenantResponses[keyof OpenapiAdminNewTenantResponses];

export type OpenapiAdminRemoveTenantData = {
    body: OpenapiAdminDeleteTenant;
    path?: never;
    query?: never;
    url: '/api/v1/admin/tenant/delete';
};

export type OpenapiAdminRemoveTenantErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiAdminRemoveTenantError = OpenapiAdminRemoveTenantErrors[keyof OpenapiAdminRemoveTenantErrors];

export type OpenapiAdminRemoveTenantResponses = {
    /**
     * Tenant deleted successfully
     */
    200: OpenapiUtilsApiResponse_String_;
};

export type OpenapiAdminRemoveTenantResponse = OpenapiAdminRemoveTenantResponses[keyof OpenapiAdminRemoveTenantResponses];

export type OpenapiAdminAllTenantsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/tenant/list';
};

export type OpenapiAdminAllTenantsErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiAdminAllTenantsError = OpenapiAdminAllTenantsErrors[keyof OpenapiAdminAllTenantsErrors];

export type OpenapiAdminAllTenantsResponses = {
    /**
     * All tenant names
     */
    200: OpenapiUtilsApiResponse_allocVecVec_String__;
};

export type OpenapiAdminAllTenantsResponse = OpenapiAdminAllTenantsResponses[keyof OpenapiAdminAllTenantsResponses];

export type OpenapiTotpListTotpData = {
    body: OpenapiTotpAllTotpRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/totp/list';
};

export type OpenapiTotpListTotpErrors = {
    /**
     * Failed
     */
    401: OpenapiUtilsApiProblem;
};

export type OpenapiTotpListTotpError = OpenapiTotpListTotpErrors[keyof OpenapiTotpListTotpErrors];

export type OpenapiTotpListTotpResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse_allocVecVec_openapiTotpTotpEntry__;
};

export type OpenapiTotpListTotpResponse = OpenapiTotpListTotpResponses[keyof OpenapiTotpListTotpResponses];

export type OpenapiTotpRemoveTotpData = {
    body: OpenapiTotpRemoveTotpRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/totp/remove';
};

export type OpenapiTotpRemoveTotpErrors = {
    /**
     * Failed
     */
    401: OpenapiUtilsApiProblem;
};

export type OpenapiTotpRemoveTotpError = OpenapiTotpRemoveTotpErrors[keyof OpenapiTotpRemoveTotpErrors];

export type OpenapiTotpRemoveTotpResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiTotpRemoveTotpResponse = OpenapiTotpRemoveTotpResponses[keyof OpenapiTotpRemoveTotpResponses];

export type OpenapiUserActivateUserData = {
    body: OpenapiUserActivateUser;
    path?: never;
    query?: never;
    url: '/api/v1/admin/user/activate';
};

export type OpenapiUserActivateUserErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiUserActivateUserError = OpenapiUserActivateUserErrors[keyof OpenapiUserActivateUserErrors];

export type OpenapiUserActivateUserResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiUserActivateUserResponse = OpenapiUserActivateUserResponses[keyof OpenapiUserActivateUserResponses];

export type OpenapiUserActivateSelfData = {
    body: OpenapiUserActivateSelf;
    path?: never;
    query?: never;
    url: '/api/v1/admin/user/activate/self';
};

export type OpenapiUserActivateSelfErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiUserActivateSelfError = OpenapiUserActivateSelfErrors[keyof OpenapiUserActivateSelfErrors];

export type OpenapiUserActivateSelfResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiUserActivateSelfResponse = OpenapiUserActivateSelfResponses[keyof OpenapiUserActivateSelfResponses];

export type OpenapiUserAddRoleData = {
    body: OpenapiUserAddRole;
    path?: never;
    query?: never;
    url: '/api/v1/admin/user/add_role';
};

export type OpenapiUserAddRoleErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
    /**
     * Level gate refused the role
     */
    403: OpenapiUtilsApiProblem;
};

export type OpenapiUserAddRoleError = OpenapiUserAddRoleErrors[keyof OpenapiUserAddRoleErrors];

export type OpenapiUserAddRoleResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiUserAddRoleResponse = OpenapiUserAddRoleResponses[keyof OpenapiUserAddRoleResponses];

export type OpenapiUserAddUserData = {
    body: OpenapiUserAddUser;
    path?: never;
    query?: never;
    url: '/api/v1/admin/user/create';
};

export type OpenapiUserAddUserErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiUserAddUserError = OpenapiUserAddUserErrors[keyof OpenapiUserAddUserErrors];

export type OpenapiUserAddUserResponses = {
    /**
     * User created successfully
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiUserAddUserResponse = OpenapiUserAddUserResponses[keyof OpenapiUserAddUserResponses];

export type OpenapiUserDeleteUserData = {
    body: OpenapiUserDeleteUser;
    path?: never;
    query?: never;
    url: '/api/v1/admin/user/delete';
};

export type OpenapiUserDeleteUserErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiUserDeleteUserError = OpenapiUserDeleteUserErrors[keyof OpenapiUserDeleteUserErrors];

export type OpenapiUserDeleteUserResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiUserDeleteUserResponse = OpenapiUserDeleteUserResponses[keyof OpenapiUserDeleteUserResponses];

export type OpenapiUserDeleteSelfData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/user/delete/self';
};

export type OpenapiUserDeleteSelfErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiUserDeleteSelfError = OpenapiUserDeleteSelfErrors[keyof OpenapiUserDeleteSelfErrors];

export type OpenapiUserDeleteSelfResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiUserDeleteSelfResponse = OpenapiUserDeleteSelfResponses[keyof OpenapiUserDeleteSelfResponses];

export type OpenapiUserAllUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/user/list';
};

export type OpenapiUserAllUsersErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiUserAllUsersError = OpenapiUserAllUsersErrors[keyof OpenapiUserAllUsersErrors];

export type OpenapiUserAllUsersResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse_allocVecVec_String__;
};

export type OpenapiUserAllUsersResponse = OpenapiUserAllUsersResponses[keyof OpenapiUserAllUsersResponses];

export type OpenapiEmailRemoveData = {
    body?: never;
    path?: never;
    query: {
        /**
         * User name
         */
        name: string;
        /**
         * User mobile
         */
        mobile: string;
    };
    url: '/api/v1/admin/user/remove_email';
};

export type OpenapiEmailRemoveErrors = {
    /**
     * Failed
     */
    401: OpenapiEmailEmailResponse;
};

export type OpenapiEmailRemoveError = OpenapiEmailRemoveErrors[keyof OpenapiEmailRemoveErrors];

export type OpenapiEmailRemoveResponses = {
    /**
     * Success
     */
    200: OpenapiEmailEmailResponse;
};

export type OpenapiEmailRemoveResponse = OpenapiEmailRemoveResponses[keyof OpenapiEmailRemoveResponses];

export type OpenapiOtpRemoveData = {
    body?: never;
    path?: never;
    query: {
        /**
         * User name
         */
        name: string;
        /**
         * User mobile
         */
        mobile: string;
    };
    url: '/api/v1/admin/user/remove_mobile';
};

export type OpenapiOtpRemoveErrors = {
    /**
     * Failed
     */
    401: OpenapiOtpMobileResponse;
};

export type OpenapiOtpRemoveError = OpenapiOtpRemoveErrors[keyof OpenapiOtpRemoveErrors];

export type OpenapiOtpRemoveResponses = {
    /**
     * Success
     */
    200: OpenapiOtpMobileResponse;
};

export type OpenapiOtpRemoveResponse = OpenapiOtpRemoveResponses[keyof OpenapiOtpRemoveResponses];

export type OpenapiUserRemoveRoleData = {
    body: OpenapiUserRemoveRole;
    path?: never;
    query?: never;
    url: '/api/v1/admin/user/remove_role';
};

export type OpenapiUserRemoveRoleErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
    /**
     * Level gate refused the role
     */
    403: OpenapiUtilsApiProblem;
};

export type OpenapiUserRemoveRoleError = OpenapiUserRemoveRoleErrors[keyof OpenapiUserRemoveRoleErrors];

export type OpenapiUserRemoveRoleResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiUserRemoveRoleResponse = OpenapiUserRemoveRoleResponses[keyof OpenapiUserRemoveRoleResponses];

export type OpenapiSocialRemoveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/user/remove_social';
};

export type OpenapiSocialRemoveErrors = {
    /**
     * Failure
     */
    400: unknown;
};

export type OpenapiSocialRemoveResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type OpenapiUserUserRolesData = {
    body: OpenapiUserUserRoleRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/user/roles';
};

export type OpenapiUserUserRolesErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiUserUserRolesError = OpenapiUserUserRolesErrors[keyof OpenapiUserUserRolesErrors];

export type OpenapiUserUserRolesResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse_allocVecVec_String__;
};

export type OpenapiUserUserRolesResponse = OpenapiUserUserRolesResponses[keyof OpenapiUserUserRolesResponses];

export type OpenapiEmailRequestData = {
    body: OpenapiEmailReqRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/email/request';
};

export type OpenapiEmailRequestErrors = {
    /**
     * Failed
     */
    401: OpenapiEmailEmailResponse;
};

export type OpenapiEmailRequestError = OpenapiEmailRequestErrors[keyof OpenapiEmailRequestErrors];

export type OpenapiEmailRequestResponses = {
    /**
     * Success
     */
    200: OpenapiEmailEmailResponse;
};

export type OpenapiEmailRequestResponse = OpenapiEmailRequestResponses[keyof OpenapiEmailRequestResponses];

export type OpenapiEmailVerifyData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Unique token
         */
        token: string;
        /**
         * User name
         */
        name: string;
        /**
         * User email
         */
        email: string;
    };
    url: '/api/v1/auth/email/verify';
};

export type OpenapiEmailVerifyErrors = {
    /**
     * Failed
     */
    401: OpenapiEmailEmailResponse;
};

export type OpenapiEmailVerifyError = OpenapiEmailVerifyErrors[keyof OpenapiEmailVerifyErrors];

export type OpenapiEmailVerifyResponses = {
    /**
     * Success
     */
    200: OpenapiEmailEmailResponse;
};

export type OpenapiEmailVerifyResponse = OpenapiEmailVerifyResponses[keyof OpenapiEmailVerifyResponses];

export type OpenapiVerifyLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type OpenapiVerifyLogoutErrors = {
    /**
     * Unauthorized
     */
    401: OpenapiUtilsApiProblem;
};

export type OpenapiVerifyLogoutError = OpenapiVerifyLogoutErrors[keyof OpenapiVerifyLogoutErrors];

export type OpenapiVerifyLogoutResponses = {
    /**
     * Authorized
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiVerifyLogoutResponse = OpenapiVerifyLogoutResponses[keyof OpenapiVerifyLogoutResponses];

export type OpenapiOtpRequestData = {
    body: OpenapiOtpReqRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/otp/request';
};

export type OpenapiOtpRequestErrors = {
    /**
     * Failed
     */
    401: OpenapiOtpMobileResponse;
};

export type OpenapiOtpRequestError = OpenapiOtpRequestErrors[keyof OpenapiOtpRequestErrors];

export type OpenapiOtpRequestResponses = {
    /**
     * Success
     */
    200: OpenapiOtpMobileResponse;
};

export type OpenapiOtpRequestResponse = OpenapiOtpRequestResponses[keyof OpenapiOtpRequestResponses];

export type OpenapiOtpVerifyData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Unique token
         */
        token: string;
        /**
         * User name
         */
        name: string;
        /**
         * User mobile
         */
        mobile: string;
        /**
         * OTP code
         */
        code: string;
    };
    url: '/api/v1/auth/otp/verify';
};

export type OpenapiOtpVerifyErrors = {
    /**
     * Failed
     */
    401: OpenapiOtpMobileResponse;
};

export type OpenapiOtpVerifyError = OpenapiOtpVerifyErrors[keyof OpenapiOtpVerifyErrors];

export type OpenapiOtpVerifyResponses = {
    /**
     * Success
     */
    200: OpenapiOtpMobileResponse;
};

export type OpenapiOtpVerifyResponse = OpenapiOtpVerifyResponses[keyof OpenapiOtpVerifyResponses];

export type OpenapiPasskeyRemoveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/passkey/remove';
};

export type OpenapiPasskeyRemoveErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type OpenapiPasskeyRemoveResponses = {
    /**
     * Passkeys deactivated
     */
    200: OpenapiUtilsApiResponse_String_;
};

export type OpenapiPasskeyRemoveResponse = OpenapiPasskeyRemoveResponses[keyof OpenapiPasskeyRemoveResponses];

export type OpenapiPasskeyRequestData = {
    body: OpenapiPasskeyPasskeyRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/passkey/request';
};

export type OpenapiPasskeyRequestErrors = {
    /**
     * Failed or no tenant found
     */
    401: unknown;
};

export type OpenapiPasskeyRequestResponses = {
    /**
     * Registration started successfully
     */
    200: OpenapiPasskeyPasskeyResponse;
};

export type OpenapiPasskeyRequestResponse = OpenapiPasskeyRequestResponses[keyof OpenapiPasskeyRequestResponses];

export type OpenapiPasskeyVerifyData = {
    body: OpenapiPasskeyVerifyRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/passkey/verify';
};

export type OpenapiPasskeyVerifyErrors = {
    /**
     * Verification failed or expired token
     */
    401: unknown;
};

export type OpenapiPasskeyVerifyResponses = {
    /**
     * Login successful
     */
    200: OpenapiUtilsApiResponse_String_;
};

export type OpenapiPasskeyVerifyResponse = OpenapiPasskeyVerifyResponses[keyof OpenapiPasskeyVerifyResponses];

export type OpenapiVerifyRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type OpenapiVerifyRefreshErrors = {
    /**
     * Unauthorized
     */
    401: OpenapiUtilsApiProblem;
};

export type OpenapiVerifyRefreshError = OpenapiVerifyRefreshErrors[keyof OpenapiVerifyRefreshErrors];

export type OpenapiVerifyRefreshResponses = {
    /**
     * Authorized
     */
    200: OpenapiUtilsApiResponse_String_;
};

export type OpenapiVerifyRefreshResponse = OpenapiVerifyRefreshResponses[keyof OpenapiVerifyRefreshResponses];

export type OpenapiSocialRedeemData = {
    body: OpenapiSocialRedeemRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/social/redeem';
};

export type OpenapiSocialRedeemErrors = {
    /**
     * Unknown, expired, or already-redeemed code
     */
    401: unknown;
};

export type OpenapiSocialRedeemResponses = {
    /**
     * ok — session JWT issued
     */
    200: unknown;
};

export type OpenapiSocialRequestData = {
    body?: never;
    path: {
        /**
         * Provider id, e.g. `github`
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/auth/social/{id}/request';
};

export type OpenapiSocialRequest2Data = {
    body?: never;
    path: {
        /**
         * Provider id, e.g. `github`
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/auth/social/{id}/request';
};

export type OpenapiSocialVerifyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/auth/social/{id}/verify';
};

export type OpenapiSocialVerifyErrors = {
    /**
     * Missing code/state, invalid or expired state, or exchange/user failure
     */
    400: unknown;
    /**
     * State mismatch — possible CSRF attack
     */
    401: unknown;
};

export type OpenapiSocialVerify2Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/auth/social/{id}/verify';
};

export type OpenapiSocialVerify2Errors = {
    /**
     * Missing code/state, invalid or expired state, or exchange/user failure
     */
    400: unknown;
    /**
     * State mismatch — possible CSRF attack
     */
    401: unknown;
};

export type OpenapiTotpEnrollData = {
    body: OpenapiTotpEnrollTotpRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/totp/enroll';
};

export type OpenapiTotpEnrollErrors = {
    /**
     * Failed
     */
    401: OpenapiUtilsApiProblem;
};

export type OpenapiTotpEnrollError = OpenapiTotpEnrollErrors[keyof OpenapiTotpEnrollErrors];

export type OpenapiTotpEnrollResponses = {
    /**
     * Success
     */
    200: OpenapiTotpEnrollTotpResponse;
};

export type OpenapiTotpEnrollResponse = OpenapiTotpEnrollResponses[keyof OpenapiTotpEnrollResponses];

export type OpenapiTotpEnroll2Data = {
    body: OpenapiTotpEnrollTotpRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/totp/enroll';
};

export type OpenapiTotpEnroll2Errors = {
    /**
     * Failed
     */
    401: OpenapiUtilsApiProblem;
};

export type OpenapiTotpEnroll2Error = OpenapiTotpEnroll2Errors[keyof OpenapiTotpEnroll2Errors];

export type OpenapiTotpEnroll2Responses = {
    /**
     * Success
     */
    200: OpenapiTotpEnrollTotpResponse;
};

export type OpenapiTotpEnroll2Response = OpenapiTotpEnroll2Responses[keyof OpenapiTotpEnroll2Responses];

export type OpenapiTotpVerifyData = {
    body: OpenapiTotpVerifyTotpRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/totp/verify';
};

export type OpenapiTotpVerifyErrors = {
    /**
     * Failed
     */
    401: OpenapiUtilsApiProblem;
};

export type OpenapiTotpVerifyError = OpenapiTotpVerifyErrors[keyof OpenapiTotpVerifyErrors];

export type OpenapiTotpVerifyResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse_String_;
};

export type OpenapiTotpVerifyResponse = OpenapiTotpVerifyResponses[keyof OpenapiTotpVerifyResponses];

export type OpenapiTotpVerify2Data = {
    body: OpenapiTotpVerifyTotpRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/totp/verify';
};

export type OpenapiTotpVerify2Errors = {
    /**
     * Failed
     */
    401: OpenapiUtilsApiProblem;
};

export type OpenapiTotpVerify2Error = OpenapiTotpVerify2Errors[keyof OpenapiTotpVerify2Errors];

export type OpenapiTotpVerify2Responses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse_String_;
};

export type OpenapiTotpVerify2Response = OpenapiTotpVerify2Responses[keyof OpenapiTotpVerify2Responses];

export type OpenapiVerifyVerifyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/verify';
};

export type OpenapiVerifyVerifyErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type OpenapiVerifyVerifyResponses = {
    /**
     * Authorized
     */
    200: unknown;
};

export type OpenapiVerifyVerify2Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/verify';
};

export type OpenapiVerifyVerify2Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type OpenapiVerifyVerify2Responses = {
    /**
     * Authorized
     */
    200: unknown;
};

export type OpenapiRouterHealthyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/healthy';
};

export type OpenapiRouterHealthyResponses = {
    /**
     * Response with json format data
     */
    200: OpenapiRouterHealthyResponse;
};

export type OpenapiRouterHealthyResponse2 = OpenapiRouterHealthyResponses[keyof OpenapiRouterHealthyResponses];
