// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type OpenapiAdminAddDomain = {
    domain: string;
    tenant: string;
};

export type OpenapiAdminDeleteDomain = {
    domain: string;
    tenant: string;
};

export type OpenapiAdminDeleteTenant = {
    name: string;
};

export type OpenapiAdminNewTenant = {
    /**
     * First admin user; created and granted the builtin `admin` role.
     */
    admin?: string | null;
    /**
     * Optional verified email for the first admin (G-131). Without it the
     * new tenant's admin is credential-less and can never sign in: strict
     * signup refuses the pre-existing username, and every attach path
     * (SCIM client, `user/attach_email`) itself requires an admin session
     * for THIS tenant. The creator vouches for the address — it lands as
     * a verified credential, and the magic-link ceremony mints the first
     * session.
     */
    admin_email?: string | null;
    /**
     * First domain of the new tenant; the standard admin policy set is
     * bound to it. Without a domain the
     * tenant stays default-deny locked until one is added.
     */
    domain?: string | null;
    name: string;
};

export type OpenapiDbHttpMethod = 'GET' | 'POST' | 'PUT' | 'OPTIONS' | 'DELETE' | 'PATCH' | 'CONNECT' | 'HEAD' | 'TRACE';

export type OpenapiEmailAttachEmailRequest = {
    email: string;
    name: string;
};

export type OpenapiEmailEmailAddRequest = {
    email: string;
};

export type OpenapiEmailEmailAddVerifyRequest = {
    email: string;
    token: string;
};

export type OpenapiEmailEmailResponse = {
    code: number;
    jwt?: string | null;
    msg: string;
    ok: boolean;
};

export type OpenapiEmailReqRequest = {
    /**
     * Return context parked on the login page: an in-flight OIDC
     * `/authorize` (client_id + state) or a plain same-origin redirect.
     * Embedded in the emailed link so the magic-link round-trip can resume
     * it after verify — safe because resume/redirect targets are validated
     * server-side (parked authorize) or same-origin-checked client-side.
     */
    client_id?: string | null;
    email: string;
    name: string;
    redirect_uri?: string | null;
    state?: string | null;
};

export type OpenapiIdpDeleteOauth2Client = {
    client_id: string;
};

export type OpenapiIdpNewOauth2Client = {
    client_id: string;
    default_scopes: string;
    grant_types: string;
    redirect_uris: string;
    response_types: string;
    secret: string;
    token_endpoint_auth_method: string;
};

export type OpenapiIdpOAuth2ClientDto = {
    active: boolean;
    created_at: string;
    domain_id: string;
    grant_types: string;
    id: string;
    redirect_uris: string;
    response_types: string;
    scope: string;
    secret_grace_until?: string | null;
    token_endpoint_auth_method: string;
    updated_at: string;
};

export type OpenapiKeyAddkey = {
    /**
     * The domain the key is for. H9: the AUTHENTICATED request domain is
     * authoritative — a non-empty mismatch is refused unless the caller
     * is root (level 100) AND the claimed domain is a sibling of the
     * same tenant, the only path that can seed a second domain's first
     * signing key.
     */
    domain: string;
    name: string;
};

export type OpenapiKeyDeleteKey = {
    name: string;
};

export type OpenapiKeyKeyEntry = {
    domain: string;
    name: string;
    public: string;
    /**
     * G-97: retired keys still verify outstanding tokens and stay in the
     * JWKS, but never sign new ones and cannot be deleted-while-active.
     */
    retired: boolean;
};

export type OpenapiKeyRetireKey = {
    name: string;
};

export type OpenapiOidcExtClientMetaRequest = {
    backchannel_logout_uri?: string | null;
    client_id: string;
    client_name?: string | null;
    post_logout_redirect_uris?: Array<string> | null;
};

export type OpenapiOidcExtOidcTenantConfig = {
    dcr_enabled: boolean;
};

export type OpenapiOpsHealthyResponse = {
    ok: boolean;
};

export type OpenapiOtpMobileAddRequest = {
    mobile: string;
};

export type OpenapiOtpMobileAddVerifyRequest = {
    code: string;
    token: string;
};

export type OpenapiOtpMobileResponse = {
    code: number;
    /**
     * Endpoint-dependent token field (the name is historical):
     * - `request`: an OPAQUE flow handle — NOT a JWT. Echo it back to
     * `verify` as `token`. The ceremony JWT stays server-side (H1):
     * its base64 `sub` would leak the resolved username on this
     * unauthenticated endpoint.
     * - `verify` (success): the session JWT.
     */
    jwt?: string | null;
    msg: string;
    ok: boolean;
};

export type OpenapiOtpReqRequest = {
    mobile: string;
    name: string;
};

export type OpenapiPasskeyPasskeyRequest = string;

/**
 * Response body for the registration/login challenge.
 */
export type OpenapiPasskeyPasskeyResponse = {
    publicKey: unknown;
    /**
     *  Opaque per-flow handle the client must echo back to `verify`
     * . Replaces the old username-derived cache key.
     */
    token: string;
};

export type OpenapiPasskeyRemovePasskeyRequest = {
    name: string;
};

export type OpenapiPasskeyVerifyRequest = {
    cookie?: string | null;
    credential: unknown;
    /**
     * Requested session lifetime in seconds (G-90), clamped to the
     * 15-minute ceiling — a caller may shorten its session, never
     * lengthen it. Omitted → 15 minutes.
     */
    lifetime?: number | null;
    /**
     * Flow handle from `passkey/request`: selects the cached
     * challenge. Required — without it no ceremony can be completed.
     */
    token: string;
    username: string;
};

/**
 * Request body for [`delete_policy`] — identifies a policy by its
 * resource template, HTTP method, and role. The domain is always the one
 * resolved from the request `Host`; a `domain` field present in
 * the body is ignored.
 */
export type OpenapiPolicyDeletePolicy = {
    action?: null | OpenapiDbHttpMethod;
    resource: string;
    role: string;
};

/**
 * Wire-format representation of a [`Policy`] for HTTP responses and request
 * bodies. `resource` is a slash-joined path template (e.g. `"users/{id}"`)
 * rather than the segmented `Vec<String>` stored on the model.
 */
export type OpenapiPolicyPolicyEntry = {
    action?: null | OpenapiDbHttpMethod;
    allowed: boolean;
    domain: string;
    id?: string | null;
    mfa: boolean;
    resource: string;
    role: string;
    source: OpenapiPolicySourceResolver;
    target: OpenapiPolicyTargetResolver;
};

export type OpenapiPolicySourceResolver = 'Nothing' | 'User' | 'Domain' | 'Role';

export type OpenapiPolicyTargetResolver = 'Nothing' | {
    FromPath: {
        pname: string;
    };
} | {
    FromQuery: {
        qname: string;
    };
} | {
    FromHeader: {
        hname: string;
    };
};

export type OpenapiRoleAddRole = {
    /**
     * Privilege level of the new role; must lie in `[0, caller level)`.
     */
    level: number;
    name: string;
};

export type OpenapiRoleDeleteRole = {
    name: string;
};

export type OpenapiRoleRoleEntry = {
    builtin: boolean;
    level: number;
    name: string;
};

export type OpenapiSocialAddProvider = {
    client_id: string;
    client_secret: string;
    issuer_url: string;
    name: string;
};

/**
 * The wire shape of `admin/provider/list` (G-147): `client_secret` is
 * WRITE-ONLY. The raw model used to serialize straight to the response,
 * handing every admin session (and anything logging responses) the
 * stored secret — plaintext for legacy rows, ciphertext for newer ones.
 */
export type OpenapiSocialProviderEntry = {
    client_id: string;
    id: string;
    issuer_url: string;
    scopes: Array<string>;
};

export type OpenapiSocialRedeemRequest = {
    code: string;
    /**
     * When set, the session JWT is additionally stored in an HttpOnly
     * cookie under this name (G-139: keeps the token out of JS-readable
     * storage for browser callers).
     */
    cookie?: string | null;
};

export type OpenapiSocialRemoveProvider = {
    name: string;
};

export type OpenapiTotpAllTotpRequest = {
    name?: string | null;
};

export type OpenapiTotpEnrollTotpRequest = {
    /**
     * Required when a TOTP with this name is already ACTIVE: a valid
     * current code proving possession before the active secret is
     * re-exposed. The code is consumed.
     */
    code?: string | null;
    name: string;
    user?: string | null;
};

export type OpenapiTotpEnrollTotpResponse = {
    domain: string;
    name: string;
    qr: string;
    token: string;
    uri: string;
    user: string;
};

export type OpenapiTotpRemoveTotpRequest = {
    name: string;
    totp: string;
};

export type OpenapiTotpTotpEntry = {
    active: boolean;
    name: string;
};

export type OpenapiTotpVerifyTotpRequest = {
    code: string;
    cookie?: string | null;
    /**
     * Requested session lifetime in seconds (G-90), clamped to the
     * 15-minute ceiling — a caller may shorten its session, never
     * lengthen it. Omitted → 15 minutes.
     */
    lifetime?: number | null;
    name?: string | null;
    token?: string | null;
    user: string;
};

export type OpenapiUserActivateSelf = {
    active: boolean;
};

export type OpenapiUserActivateUser = {
    active: boolean;
    user: string;
};

export type OpenapiUserAddRole = {
    role: string;
    user: string;
};

export type OpenapiUserAddUser = {
    name: string;
};

export type OpenapiUserDeleteUser = {
    user: string;
};

export type OpenapiUserRemoveRole = {
    role: string;
    user: string;
};

export type OpenapiUtilsApiProblem = {
    detail?: string | null;
    status: number;
    type: string;
};

export type OpenapiUtilsApiResponse____ = {
    data: unknown;
    ok: boolean;
};

export type OpenapiUtilsApiResponse_String_ = {
    data: string;
    ok: boolean;
};

export type OpenapiUtilsApiResponse_allocVecVec_String__ = {
    data: Array<string>;
    ok: boolean;
};

export type OpenapiUtilsApiResponse_openapiOidcExtOidcTenantConfig_ = {
    data: OpenapiOidcExtOidcTenantConfig;
    ok: boolean;
};

export type OpenapiUtilsApiResponse_openapiUtilsPage_String__ = {
    data: OpenapiUtilsPage_String_;
    ok: boolean;
};

export type OpenapiUtilsApiResponse_openapiUtilsPage_openapiIdpOAuth2ClientDto__ = {
    data: OpenapiUtilsPage_openapiIdpOAuth2ClientDto_;
    ok: boolean;
};

export type OpenapiUtilsApiResponse_openapiUtilsPage_openapiKeyKeyEntry__ = {
    data: OpenapiUtilsPage_openapiKeyKeyEntry_;
    ok: boolean;
};

export type OpenapiUtilsApiResponse_openapiUtilsPage_openapiPolicyPolicyEntry__ = {
    data: OpenapiUtilsPage_openapiPolicyPolicyEntry_;
    ok: boolean;
};

export type OpenapiUtilsApiResponse_openapiUtilsPage_openapiRoleRoleEntry__ = {
    data: OpenapiUtilsPage_openapiRoleRoleEntry_;
    ok: boolean;
};

export type OpenapiUtilsApiResponse_openapiUtilsPage_openapiSocialProviderEntry__ = {
    data: OpenapiUtilsPage_openapiSocialProviderEntry_;
    ok: boolean;
};

export type OpenapiUtilsApiResponse_openapiUtilsPage_openapiTotpTotpEntry__ = {
    data: OpenapiUtilsPage_openapiTotpTotpEntry_;
    ok: boolean;
};

export type OpenapiUtilsApiResponse_openapiVerifySessionInfo_ = {
    data: OpenapiVerifySessionInfo;
    ok: boolean;
};

/**
 * Pagination envelope for list endpoints. `next_offset` is `Some` only when
 * more rows follow this page, so clients can loop without a total count.
 */
export type OpenapiUtilsPage_String_ = {
    items: Array<string>;
    limit: number;
    next_offset?: number | null;
    offset: number;
};

/**
 * Pagination envelope for list endpoints. `next_offset` is `Some` only when
 * more rows follow this page, so clients can loop without a total count.
 */
export type OpenapiUtilsPage_openapiIdpOAuth2ClientDto_ = {
    items: Array<OpenapiIdpOAuth2ClientDto>;
    limit: number;
    next_offset?: number | null;
    offset: number;
};

/**
 * Pagination envelope for list endpoints. `next_offset` is `Some` only when
 * more rows follow this page, so clients can loop without a total count.
 */
export type OpenapiUtilsPage_openapiKeyKeyEntry_ = {
    items: Array<OpenapiKeyKeyEntry>;
    limit: number;
    next_offset?: number | null;
    offset: number;
};

/**
 * Pagination envelope for list endpoints. `next_offset` is `Some` only when
 * more rows follow this page, so clients can loop without a total count.
 */
export type OpenapiUtilsPage_openapiPolicyPolicyEntry_ = {
    items: Array<OpenapiPolicyPolicyEntry>;
    limit: number;
    next_offset?: number | null;
    offset: number;
};

/**
 * Pagination envelope for list endpoints. `next_offset` is `Some` only when
 * more rows follow this page, so clients can loop without a total count.
 */
export type OpenapiUtilsPage_openapiRoleRoleEntry_ = {
    items: Array<OpenapiRoleRoleEntry>;
    limit: number;
    next_offset?: number | null;
    offset: number;
};

/**
 * Pagination envelope for list endpoints. `next_offset` is `Some` only when
 * more rows follow this page, so clients can loop without a total count.
 */
export type OpenapiUtilsPage_openapiSocialProviderEntry_ = {
    items: Array<OpenapiSocialProviderEntry>;
    limit: number;
    next_offset?: number | null;
    offset: number;
};

/**
 * Pagination envelope for list endpoints. `next_offset` is `Some` only when
 * more rows follow this page, so clients can loop without a total count.
 */
export type OpenapiUtilsPage_openapiTotpTotpEntry_ = {
    items: Array<OpenapiTotpTotpEntry>;
    limit: number;
    next_offset?: number | null;
    offset: number;
};

/**
 * The current session's identity, for first-party frontends that no
 * longer hold a readable JWT (G-139 moved it into an HttpOnly cookie):
 * the admin console's MFA/Account tabs and the step-up flows need to
 * know WHO the session belongs to (G-138/G-162).
 */
export type OpenapiVerifySessionInfo = {
    auth_time?: number | null;
    domain: string;
    /**
     * Factors proven at `auth_time` (feeds amr/acr and the policy
     * engine's MFA gate).
     */
    mfa: Array<string>;
    roles: Array<string>;
    user: string;
    username: string;
};

export type OpenapiAdminAddDomainData = {
    body: OpenapiAdminAddDomain;
    path?: never;
    query?: never;
    url: '/api/v1/admin/domain/create';
};

export type OpenapiAdminAddDomainErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiAdminAddDomainError = OpenapiAdminAddDomainErrors[keyof OpenapiAdminAddDomainErrors];

export type OpenapiAdminAddDomainResponses = {
    /**
     * Domain created successfully
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiAdminAddDomainResponse = OpenapiAdminAddDomainResponses[keyof OpenapiAdminAddDomainResponses];

export type OpenapiAdminDeleteDomainData = {
    body: OpenapiAdminDeleteDomain;
    path?: never;
    query?: never;
    url: '/api/v1/admin/domain/delete';
};

export type OpenapiAdminDeleteDomainErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiAdminDeleteDomainError = OpenapiAdminDeleteDomainErrors[keyof OpenapiAdminDeleteDomainErrors];

export type OpenapiAdminDeleteDomainResponses = {
    /**
     * Domain removed successfully
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiAdminDeleteDomainResponse = OpenapiAdminDeleteDomainResponses[keyof OpenapiAdminDeleteDomainResponses];

export type OpenapiAdminAllDomainsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Max items per page (server-enforced default and cap)
         */
        limit?: number;
        /**
         * Number of items to skip
         */
        offset?: number;
    };
    url: '/api/v1/admin/domain/list';
};

export type OpenapiAdminAllDomainsErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiAdminAllDomainsError = OpenapiAdminAllDomainsErrors[keyof OpenapiAdminAllDomainsErrors];

export type OpenapiAdminAllDomainsResponses = {
    /**
     * All domain names of the tenant
     */
    200: OpenapiUtilsApiResponse_openapiUtilsPage_String__;
};

export type OpenapiAdminAllDomainsResponse = OpenapiAdminAllDomainsResponses[keyof OpenapiAdminAllDomainsResponses];

export type OpenapiKeyAddKeyData = {
    body: OpenapiKeyAddkey;
    path?: never;
    query?: never;
    url: '/api/v1/admin/key/create';
};

export type OpenapiKeyAddKeyErrors = {
    /**
     * Bad request, or non-root cross-domain claim
     */
    400: OpenapiUtilsApiProblem;
    /**
     * Cross-domain claim without a verified session
     */
    401: OpenapiUtilsApiProblem;
};

export type OpenapiKeyAddKeyError = OpenapiKeyAddKeyErrors[keyof OpenapiKeyAddKeyErrors];

export type OpenapiKeyAddKeyResponses = {
    /**
     * Scope created successfully
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiKeyAddKeyResponse = OpenapiKeyAddKeyResponses[keyof OpenapiKeyAddKeyResponses];

export type OpenapiKeyDeleteKeyData = {
    body: OpenapiKeyDeleteKey;
    path?: never;
    query?: never;
    url: '/api/v1/admin/key/delete';
};

export type OpenapiKeyDeleteKeyErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
    /**
     * Key belongs to another domain
     */
    403: OpenapiUtilsApiProblem;
};

export type OpenapiKeyDeleteKeyError = OpenapiKeyDeleteKeyErrors[keyof OpenapiKeyDeleteKeyErrors];

export type OpenapiKeyDeleteKeyResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiKeyDeleteKeyResponse = OpenapiKeyDeleteKeyResponses[keyof OpenapiKeyDeleteKeyResponses];

export type OpenapiKeyAllKeysData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Max items per page (server-enforced default and cap)
         */
        limit?: number;
        /**
         * Number of items to skip
         */
        offset?: number;
    };
    url: '/api/v1/admin/key/list';
};

export type OpenapiKeyAllKeysErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiKeyAllKeysError = OpenapiKeyAllKeysErrors[keyof OpenapiKeyAllKeysErrors];

export type OpenapiKeyAllKeysResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse_openapiUtilsPage_openapiKeyKeyEntry__;
};

export type OpenapiKeyAllKeysResponse = OpenapiKeyAllKeysResponses[keyof OpenapiKeyAllKeysResponses];

export type OpenapiKeyRetireKeyData = {
    body: OpenapiKeyRetireKey;
    path?: never;
    query?: never;
    url: '/api/v1/admin/key/retire';
};

export type OpenapiKeyRetireKeyErrors = {
    /**
     * Bad request, or the domain's last active key
     */
    400: OpenapiUtilsApiProblem;
    /**
     * Key belongs to another domain
     */
    403: OpenapiUtilsApiProblem;
};

export type OpenapiKeyRetireKeyError = OpenapiKeyRetireKeyErrors[keyof OpenapiKeyRetireKeyErrors];

export type OpenapiKeyRetireKeyResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiKeyRetireKeyResponse = OpenapiKeyRetireKeyResponses[keyof OpenapiKeyRetireKeyResponses];

export type OpenapiOpsMetricsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/metrics';
};

export type OpenapiOpsMetricsResponses = {
    /**
     * Prometheus text exposition format
     */
    200: string;
};

export type OpenapiOpsMetricsResponse = OpenapiOpsMetricsResponses[keyof OpenapiOpsMetricsResponses];

export type OpenapiIdpNewOauth2ClientData = {
    body: OpenapiIdpNewOauth2Client;
    path?: never;
    query?: never;
    url: '/api/v1/admin/oauth2client/create';
};

export type OpenapiIdpNewOauth2ClientErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiIdpNewOauth2ClientError = OpenapiIdpNewOauth2ClientErrors[keyof OpenapiIdpNewOauth2ClientErrors];

export type OpenapiIdpNewOauth2ClientResponses = {
    /**
     * Client created successfully
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiIdpNewOauth2ClientResponse = OpenapiIdpNewOauth2ClientResponses[keyof OpenapiIdpNewOauth2ClientResponses];

export type OpenapiIdpDeleteOauth2ClientData = {
    body: OpenapiIdpDeleteOauth2Client;
    path?: never;
    query?: never;
    url: '/api/v1/admin/oauth2client/delete';
};

export type OpenapiIdpDeleteOauth2ClientErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiIdpDeleteOauth2ClientError = OpenapiIdpDeleteOauth2ClientErrors[keyof OpenapiIdpDeleteOauth2ClientErrors];

export type OpenapiIdpDeleteOauth2ClientResponses = {
    /**
     * Client deactivated
     */
    200: OpenapiUtilsApiResponse_String_;
};

export type OpenapiIdpDeleteOauth2ClientResponse = OpenapiIdpDeleteOauth2ClientResponses[keyof OpenapiIdpDeleteOauth2ClientResponses];

export type OpenapiIdpListOauth2ClientsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Max items per page (server-enforced default and cap)
         */
        limit?: number;
        /**
         * Number of items to skip
         */
        offset?: number;
    };
    url: '/api/v1/admin/oauth2client/list';
};

export type OpenapiIdpListOauth2ClientsErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiIdpListOauth2ClientsError = OpenapiIdpListOauth2ClientsErrors[keyof OpenapiIdpListOauth2ClientsErrors];

export type OpenapiIdpListOauth2ClientsResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse_openapiUtilsPage_openapiIdpOAuth2ClientDto__;
};

export type OpenapiIdpListOauth2ClientsResponse = OpenapiIdpListOauth2ClientsResponses[keyof OpenapiIdpListOauth2ClientsResponses];

export type OpenapiOidcExtSetClientMetaData = {
    body: OpenapiOidcExtClientMetaRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/oauth2client/meta';
};

export type OpenapiOidcExtSetClientMetaErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiOidcExtSetClientMetaError = OpenapiOidcExtSetClientMetaErrors[keyof OpenapiOidcExtSetClientMetaErrors];

export type OpenapiOidcExtSetClientMetaResponses = {
    /**
     * Metadata saved
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiOidcExtSetClientMetaResponse = OpenapiOidcExtSetClientMetaResponses[keyof OpenapiOidcExtSetClientMetaResponses];

export type OpenapiOidcExtOidcConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/oidc/config';
};

export type OpenapiOidcExtOidcConfigErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiOidcExtOidcConfigError = OpenapiOidcExtOidcConfigErrors[keyof OpenapiOidcExtOidcConfigErrors];

export type OpenapiOidcExtOidcConfigResponses = {
    /**
     * Current configuration
     */
    200: OpenapiUtilsApiResponse_openapiOidcExtOidcTenantConfig_;
};

export type OpenapiOidcExtOidcConfigResponse = OpenapiOidcExtOidcConfigResponses[keyof OpenapiOidcExtOidcConfigResponses];

export type OpenapiOidcExtSetOidcConfigData = {
    body: OpenapiOidcExtOidcTenantConfig;
    path?: never;
    query?: never;
    url: '/api/v1/admin/oidc/config';
};

export type OpenapiOidcExtSetOidcConfigErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiOidcExtSetOidcConfigError = OpenapiOidcExtSetOidcConfigErrors[keyof OpenapiOidcExtSetOidcConfigErrors];

export type OpenapiOidcExtSetOidcConfigResponses = {
    /**
     * Configuration updated
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiOidcExtSetOidcConfigResponse = OpenapiOidcExtSetOidcConfigResponses[keyof OpenapiOidcExtSetOidcConfigResponses];

export type OpenapiPolicyAddPolicyData = {
    body: OpenapiPolicyPolicyEntry;
    path?: never;
    query?: never;
    url: '/api/v1/admin/policy/create';
};

export type OpenapiPolicyAddPolicyErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
    /**
     * Level or resource-power gate refused
     */
    403: OpenapiUtilsApiProblem;
};

export type OpenapiPolicyAddPolicyError = OpenapiPolicyAddPolicyErrors[keyof OpenapiPolicyAddPolicyErrors];

export type OpenapiPolicyAddPolicyResponses = {
    /**
     * Policy created successfully
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiPolicyAddPolicyResponse = OpenapiPolicyAddPolicyResponses[keyof OpenapiPolicyAddPolicyResponses];

export type OpenapiPolicyDeletePolicyData = {
    body: OpenapiPolicyDeletePolicy;
    path?: never;
    query?: never;
    url: '/api/v1/admin/policy/delete';
};

export type OpenapiPolicyDeletePolicyErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
    /**
     * Level or resource-power gate refused
     */
    403: OpenapiUtilsApiProblem;
};

export type OpenapiPolicyDeletePolicyError = OpenapiPolicyDeletePolicyErrors[keyof OpenapiPolicyDeletePolicyErrors];

export type OpenapiPolicyDeletePolicyResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiPolicyDeletePolicyResponse = OpenapiPolicyDeletePolicyResponses[keyof OpenapiPolicyDeletePolicyResponses];

export type OpenapiPolicyAllPoliciesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Max items per page (server-enforced default and cap)
         */
        limit?: number;
        /**
         * Number of items to skip
         */
        offset?: number;
    };
    url: '/api/v1/admin/policy/list';
};

export type OpenapiPolicyAllPoliciesErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiPolicyAllPoliciesError = OpenapiPolicyAllPoliciesErrors[keyof OpenapiPolicyAllPoliciesErrors];

export type OpenapiPolicyAllPoliciesResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse_openapiUtilsPage_openapiPolicyPolicyEntry__;
};

export type OpenapiPolicyAllPoliciesResponse = OpenapiPolicyAllPoliciesResponses[keyof OpenapiPolicyAllPoliciesResponses];

export type OpenapiSocialAddProviderData = {
    body: OpenapiSocialAddProvider;
    path?: never;
    query?: never;
    url: '/api/v1/admin/provider/create';
};

export type OpenapiSocialAddProviderErrors = {
    /**
     * Token exchange failed
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiSocialAddProviderError = OpenapiSocialAddProviderErrors[keyof OpenapiSocialAddProviderErrors];

export type OpenapiSocialAddProviderResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiSocialAddProviderResponse = OpenapiSocialAddProviderResponses[keyof OpenapiSocialAddProviderResponses];

export type OpenapiSocialRemoveProviderData = {
    body: OpenapiSocialRemoveProvider;
    path?: never;
    query?: never;
    url: '/api/v1/admin/provider/delete';
};

export type OpenapiSocialRemoveProviderErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiSocialRemoveProviderError = OpenapiSocialRemoveProviderErrors[keyof OpenapiSocialRemoveProviderErrors];

export type OpenapiSocialRemoveProviderResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiSocialRemoveProviderResponse = OpenapiSocialRemoveProviderResponses[keyof OpenapiSocialRemoveProviderResponses];

export type OpenapiSocialAllProvidersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Max items per page (server-enforced default and cap)
         */
        limit?: number;
        /**
         * Number of items to skip
         */
        offset?: number;
    };
    url: '/api/v1/admin/provider/list';
};

export type OpenapiSocialAllProvidersErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiSocialAllProvidersError = OpenapiSocialAllProvidersErrors[keyof OpenapiSocialAllProvidersErrors];

export type OpenapiSocialAllProvidersResponses = {
    /**
     * Success — client_secret is write-only and never returned (G-147)
     */
    200: OpenapiUtilsApiResponse_openapiUtilsPage_openapiSocialProviderEntry__;
};

export type OpenapiSocialAllProvidersResponse = OpenapiSocialAllProvidersResponses[keyof OpenapiSocialAllProvidersResponses];

export type OpenapiRoleAddRoleData = {
    body: OpenapiRoleAddRole;
    path?: never;
    query?: never;
    url: '/api/v1/admin/role/create';
};

export type OpenapiRoleAddRoleErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
    /**
     * Level gate refused the role
     */
    403: OpenapiUtilsApiProblem;
    /**
     * Role name already exists
     */
    409: OpenapiUtilsApiProblem;
};

export type OpenapiRoleAddRoleError = OpenapiRoleAddRoleErrors[keyof OpenapiRoleAddRoleErrors];

export type OpenapiRoleAddRoleResponses = {
    /**
     * Role created successfully
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiRoleAddRoleResponse = OpenapiRoleAddRoleResponses[keyof OpenapiRoleAddRoleResponses];

export type OpenapiRoleDeleteRoleData = {
    body: OpenapiRoleDeleteRole;
    path?: never;
    query?: never;
    url: '/api/v1/admin/role/delete';
};

export type OpenapiRoleDeleteRoleErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
    /**
     * Level gate refused the role
     */
    403: OpenapiUtilsApiProblem;
};

export type OpenapiRoleDeleteRoleError = OpenapiRoleDeleteRoleErrors[keyof OpenapiRoleDeleteRoleErrors];

export type OpenapiRoleDeleteRoleResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiRoleDeleteRoleResponse = OpenapiRoleDeleteRoleResponses[keyof OpenapiRoleDeleteRoleResponses];

export type OpenapiRoleAllRolesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Max items per page (server-enforced default and cap)
         */
        limit?: number;
        /**
         * Number of items to skip
         */
        offset?: number;
    };
    url: '/api/v1/admin/role/list';
};

export type OpenapiRoleAllRolesErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiRoleAllRolesError = OpenapiRoleAllRolesErrors[keyof OpenapiRoleAllRolesErrors];

export type OpenapiRoleAllRolesResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse_openapiUtilsPage_openapiRoleRoleEntry__;
};

export type OpenapiRoleAllRolesResponse = OpenapiRoleAllRolesResponses[keyof OpenapiRoleAllRolesResponses];

export type OpenapiAdminNewTenantData = {
    body: OpenapiAdminNewTenant;
    path?: never;
    query?: never;
    url: '/api/v1/admin/tenant/create';
};

export type OpenapiAdminNewTenantErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiAdminNewTenantError = OpenapiAdminNewTenantErrors[keyof OpenapiAdminNewTenantErrors];

export type OpenapiAdminNewTenantResponses = {
    /**
     * Tenant created successfully
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiAdminNewTenantResponse = OpenapiAdminNewTenantResponses[keyof OpenapiAdminNewTenantResponses];

export type OpenapiAdminRemoveTenantData = {
    body: OpenapiAdminDeleteTenant;
    path?: never;
    query?: never;
    url: '/api/v1/admin/tenant/delete';
};

export type OpenapiAdminRemoveTenantErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiAdminRemoveTenantError = OpenapiAdminRemoveTenantErrors[keyof OpenapiAdminRemoveTenantErrors];

export type OpenapiAdminRemoveTenantResponses = {
    /**
     * Tenant deleted successfully
     */
    200: OpenapiUtilsApiResponse_String_;
};

export type OpenapiAdminRemoveTenantResponse = OpenapiAdminRemoveTenantResponses[keyof OpenapiAdminRemoveTenantResponses];

export type OpenapiAdminAllTenantsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Max items per page (server-enforced default and cap)
         */
        limit?: number;
        /**
         * Number of items to skip
         */
        offset?: number;
    };
    url: '/api/v1/admin/tenant/list';
};

export type OpenapiAdminAllTenantsErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiAdminAllTenantsError = OpenapiAdminAllTenantsErrors[keyof OpenapiAdminAllTenantsErrors];

export type OpenapiAdminAllTenantsResponses = {
    /**
     * All tenant names
     */
    200: OpenapiUtilsApiResponse_openapiUtilsPage_String__;
};

export type OpenapiAdminAllTenantsResponse = OpenapiAdminAllTenantsResponses[keyof OpenapiAdminAllTenantsResponses];

export type OpenapiTotpListTotpData = {
    body: OpenapiTotpAllTotpRequest;
    path?: never;
    query?: {
        /**
         * Max items per page (server-enforced default and cap)
         */
        limit?: number;
        /**
         * Number of items to skip
         */
        offset?: number;
    };
    url: '/api/v1/admin/totp/list';
};

export type OpenapiTotpListTotpErrors = {
    /**
     * Failed
     */
    401: OpenapiUtilsApiProblem;
};

export type OpenapiTotpListTotpError = OpenapiTotpListTotpErrors[keyof OpenapiTotpListTotpErrors];

export type OpenapiTotpListTotpResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse_openapiUtilsPage_openapiTotpTotpEntry__;
};

export type OpenapiTotpListTotpResponse = OpenapiTotpListTotpResponses[keyof OpenapiTotpListTotpResponses];

export type OpenapiTotpRemoveTotpData = {
    body: OpenapiTotpRemoveTotpRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/totp/remove';
};

export type OpenapiTotpRemoveTotpErrors = {
    /**
     * Failed
     */
    400: OpenapiUtilsApiProblem;
    /**
     * No verified session
     */
    401: OpenapiUtilsApiProblem;
    /**
     * Level gate refused the target user
     */
    403: OpenapiUtilsApiProblem;
};

export type OpenapiTotpRemoveTotpError = OpenapiTotpRemoveTotpErrors[keyof OpenapiTotpRemoveTotpErrors];

export type OpenapiTotpRemoveTotpResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiTotpRemoveTotpResponse = OpenapiTotpRemoveTotpResponses[keyof OpenapiTotpRemoveTotpResponses];

export type OpenapiUserActivateUserData = {
    body: OpenapiUserActivateUser;
    path?: never;
    query?: never;
    url: '/api/v1/admin/user/activate';
};

export type OpenapiUserActivateUserErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
    /**
     * No verified session
     */
    401: OpenapiUtilsApiProblem;
    /**
     * Level gate refused the target user
     */
    403: OpenapiUtilsApiProblem;
};

export type OpenapiUserActivateUserError = OpenapiUserActivateUserErrors[keyof OpenapiUserActivateUserErrors];

export type OpenapiUserActivateUserResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiUserActivateUserResponse = OpenapiUserActivateUserResponses[keyof OpenapiUserActivateUserResponses];

export type OpenapiUserActivateSelfData = {
    body: OpenapiUserActivateSelf;
    path?: never;
    query?: never;
    url: '/api/v1/admin/user/activate/self';
};

export type OpenapiUserActivateSelfErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiUserActivateSelfError = OpenapiUserActivateSelfErrors[keyof OpenapiUserActivateSelfErrors];

export type OpenapiUserActivateSelfResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiUserActivateSelfResponse = OpenapiUserActivateSelfResponses[keyof OpenapiUserActivateSelfResponses];

export type OpenapiUserAddRoleData = {
    body: OpenapiUserAddRole;
    path?: never;
    query?: never;
    url: '/api/v1/admin/user/add_role';
};

export type OpenapiUserAddRoleErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
    /**
     * Level gate refused the role
     */
    403: OpenapiUtilsApiProblem;
};

export type OpenapiUserAddRoleError = OpenapiUserAddRoleErrors[keyof OpenapiUserAddRoleErrors];

export type OpenapiUserAddRoleResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiUserAddRoleResponse = OpenapiUserAddRoleResponses[keyof OpenapiUserAddRoleResponses];

export type OpenapiEmailAttachData = {
    body: OpenapiEmailAttachEmailRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/user/attach_email';
};

export type OpenapiEmailAttachErrors = {
    /**
     * Unknown user, or the address belongs to another user
     */
    400: OpenapiEmailEmailResponse;
    /**
     * No verified session
     */
    401: OpenapiUtilsApiProblem;
    /**
     * Level gate refused the target user
     */
    403: OpenapiUtilsApiProblem;
};

export type OpenapiEmailAttachError = OpenapiEmailAttachErrors[keyof OpenapiEmailAttachErrors];

export type OpenapiEmailAttachResponses = {
    /**
     * Success
     */
    200: OpenapiEmailEmailResponse;
};

export type OpenapiEmailAttachResponse = OpenapiEmailAttachResponses[keyof OpenapiEmailAttachResponses];

export type OpenapiUserAddUserData = {
    body: OpenapiUserAddUser;
    path?: never;
    query?: never;
    url: '/api/v1/admin/user/create';
};

export type OpenapiUserAddUserErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiUserAddUserError = OpenapiUserAddUserErrors[keyof OpenapiUserAddUserErrors];

export type OpenapiUserAddUserResponses = {
    /**
     * User created successfully
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiUserAddUserResponse = OpenapiUserAddUserResponses[keyof OpenapiUserAddUserResponses];

export type OpenapiUserDeleteUserData = {
    body: OpenapiUserDeleteUser;
    path?: never;
    query?: never;
    url: '/api/v1/admin/user/delete';
};

export type OpenapiUserDeleteUserErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
    /**
     * No verified session
     */
    401: OpenapiUtilsApiProblem;
    /**
     * Level gate refused the target user
     */
    403: OpenapiUtilsApiProblem;
};

export type OpenapiUserDeleteUserError = OpenapiUserDeleteUserErrors[keyof OpenapiUserDeleteUserErrors];

export type OpenapiUserDeleteUserResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiUserDeleteUserResponse = OpenapiUserDeleteUserResponses[keyof OpenapiUserDeleteUserResponses];

export type OpenapiUserDeleteSelfData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/user/delete/self';
};

export type OpenapiUserDeleteSelfErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiUserDeleteSelfError = OpenapiUserDeleteSelfErrors[keyof OpenapiUserDeleteSelfErrors];

export type OpenapiUserDeleteSelfResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiUserDeleteSelfResponse = OpenapiUserDeleteSelfResponses[keyof OpenapiUserDeleteSelfResponses];

export type OpenapiUserAllUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Max items per page (server-enforced default and cap)
         */
        limit?: number;
        /**
         * Number of items to skip
         */
        offset?: number;
    };
    url: '/api/v1/admin/user/list';
};

export type OpenapiUserAllUsersErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiUserAllUsersError = OpenapiUserAllUsersErrors[keyof OpenapiUserAllUsersErrors];

export type OpenapiUserAllUsersResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse_openapiUtilsPage_String__;
};

export type OpenapiUserAllUsersResponse = OpenapiUserAllUsersResponses[keyof OpenapiUserAllUsersResponses];

export type OpenapiEmailRemoveData = {
    body?: never;
    path?: never;
    query: {
        /**
         * User name
         */
        name: string;
        /**
         * Email address to remove
         */
        email: string;
    };
    url: '/api/v1/admin/user/remove_email';
};

export type OpenapiEmailRemoveErrors = {
    /**
     * Failed
     */
    400: OpenapiEmailEmailResponse;
    /**
     * No verified session
     */
    401: OpenapiUtilsApiProblem;
    /**
     * Level gate refused the target user
     */
    403: OpenapiUtilsApiProblem;
};

export type OpenapiEmailRemoveError = OpenapiEmailRemoveErrors[keyof OpenapiEmailRemoveErrors];

export type OpenapiEmailRemoveResponses = {
    /**
     * Success
     */
    200: OpenapiEmailEmailResponse;
};

export type OpenapiEmailRemoveResponse = OpenapiEmailRemoveResponses[keyof OpenapiEmailRemoveResponses];

export type OpenapiOtpRemoveData = {
    body?: never;
    path?: never;
    query: {
        /**
         * User name
         */
        name: string;
        /**
         * User mobile
         */
        mobile: string;
    };
    url: '/api/v1/admin/user/remove_mobile';
};

export type OpenapiOtpRemoveErrors = {
    /**
     * Failed
     */
    400: OpenapiOtpMobileResponse;
    /**
     * No verified session
     */
    401: OpenapiUtilsApiProblem;
    /**
     * Level gate refused the target user
     */
    403: OpenapiUtilsApiProblem;
};

export type OpenapiOtpRemoveError = OpenapiOtpRemoveErrors[keyof OpenapiOtpRemoveErrors];

export type OpenapiOtpRemoveResponses = {
    /**
     * Success
     */
    200: OpenapiOtpMobileResponse;
};

export type OpenapiOtpRemoveResponse = OpenapiOtpRemoveResponses[keyof OpenapiOtpRemoveResponses];

export type OpenapiPasskeyDeactivateData = {
    body: OpenapiPasskeyRemovePasskeyRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/user/remove_passkey';
};

export type OpenapiPasskeyDeactivateErrors = {
    /**
     * Unknown user or bad request
     */
    400: OpenapiUtilsApiProblem;
    /**
     * No verified session
     */
    401: OpenapiUtilsApiProblem;
    /**
     * Level gate refused the target user
     */
    403: OpenapiUtilsApiProblem;
};

export type OpenapiPasskeyDeactivateError = OpenapiPasskeyDeactivateErrors[keyof OpenapiPasskeyDeactivateErrors];

export type OpenapiPasskeyDeactivateResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiPasskeyDeactivateResponse = OpenapiPasskeyDeactivateResponses[keyof OpenapiPasskeyDeactivateResponses];

export type OpenapiUserRemoveRoleData = {
    body: OpenapiUserRemoveRole;
    path?: never;
    query?: never;
    url: '/api/v1/admin/user/remove_role';
};

export type OpenapiUserRemoveRoleErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
    /**
     * Level gate refused the role
     */
    403: OpenapiUtilsApiProblem;
};

export type OpenapiUserRemoveRoleError = OpenapiUserRemoveRoleErrors[keyof OpenapiUserRemoveRoleErrors];

export type OpenapiUserRemoveRoleResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiUserRemoveRoleResponse = OpenapiUserRemoveRoleResponses[keyof OpenapiUserRemoveRoleResponses];

export type OpenapiSocialRemoveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/user/remove_social';
};

export type OpenapiSocialRemoveErrors = {
    /**
     * Failure
     */
    400: unknown;
    /**
     * No verified session
     */
    401: OpenapiUtilsApiProblem;
    /**
     * Level gate refused the target user
     */
    403: OpenapiUtilsApiProblem;
};

export type OpenapiSocialRemoveError = OpenapiSocialRemoveErrors[keyof OpenapiSocialRemoveErrors];

export type OpenapiSocialRemoveResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type OpenapiUserUserRolesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * User name
         */
        user: string;
    };
    url: '/api/v1/admin/user/roles';
};

export type OpenapiUserUserRolesErrors = {
    /**
     * Bad request
     */
    400: OpenapiUtilsApiProblem;
};

export type OpenapiUserUserRolesError = OpenapiUserUserRolesErrors[keyof OpenapiUserUserRolesErrors];

export type OpenapiUserUserRolesResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse_allocVecVec_String__;
};

export type OpenapiUserUserRolesResponse = OpenapiUserUserRolesResponses[keyof OpenapiUserUserRolesResponses];

export type OpenapiEmailAddData = {
    body: OpenapiEmailEmailAddRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/email/add';
};

export type OpenapiEmailAddErrors = {
    /**
     * No valid session or failed
     */
    401: OpenapiEmailEmailResponse;
    /**
     * Per-recipient dispatch budget exhausted
     */
    429: OpenapiEmailEmailResponse;
};

export type OpenapiEmailAddError = OpenapiEmailAddErrors[keyof OpenapiEmailAddErrors];

export type OpenapiEmailAddResponses = {
    /**
     * Success — confirmation link sent
     */
    200: OpenapiEmailEmailResponse;
};

export type OpenapiEmailAddResponse = OpenapiEmailAddResponses[keyof OpenapiEmailAddResponses];

export type OpenapiEmailAddVerifyData = {
    body: OpenapiEmailEmailAddVerifyRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/email/add/verify';
};

export type OpenapiEmailAddVerifyErrors = {
    /**
     * No valid session, unknown/consumed token, or the email was claimed in the meantime
     */
    401: OpenapiEmailEmailResponse;
};

export type OpenapiEmailAddVerifyError = OpenapiEmailAddVerifyErrors[keyof OpenapiEmailAddVerifyErrors];

export type OpenapiEmailAddVerifyResponses = {
    /**
     * Success — email attached to the session's account
     */
    200: OpenapiEmailEmailResponse;
};

export type OpenapiEmailAddVerifyResponse = OpenapiEmailAddVerifyResponses[keyof OpenapiEmailAddVerifyResponses];

export type OpenapiEmailRequestData = {
    body: OpenapiEmailReqRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/email/request';
};

export type OpenapiEmailRequestErrors = {
    /**
     * Failed
     */
    401: OpenapiEmailEmailResponse;
    /**
     * Per-recipient dispatch budget exhausted
     */
    429: OpenapiEmailEmailResponse;
};

export type OpenapiEmailRequestError = OpenapiEmailRequestErrors[keyof OpenapiEmailRequestErrors];

export type OpenapiEmailRequestResponses = {
    /**
     * Success
     */
    200: OpenapiEmailEmailResponse;
};

export type OpenapiEmailRequestResponse = OpenapiEmailRequestResponses[keyof OpenapiEmailRequestResponses];

export type OpenapiEmailVerifyData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Unique token
         */
        token: string;
        /**
         * User name
         */
        name: string;
        /**
         * User email
         */
        email: string;
    };
    url: '/api/v1/auth/email/verify';
};

export type OpenapiEmailVerifyErrors = {
    /**
     * Failed
     */
    401: OpenapiEmailEmailResponse;
};

export type OpenapiEmailVerifyError = OpenapiEmailVerifyErrors[keyof OpenapiEmailVerifyErrors];

export type OpenapiEmailVerifyResponses = {
    /**
     * Success
     */
    200: OpenapiEmailEmailResponse;
};

export type OpenapiEmailVerifyResponse = OpenapiEmailVerifyResponses[keyof OpenapiEmailVerifyResponses];

export type OpenapiVerifyLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type OpenapiVerifyLogoutErrors = {
    /**
     * Unauthorized
     */
    401: OpenapiUtilsApiProblem;
};

export type OpenapiVerifyLogoutError = OpenapiVerifyLogoutErrors[keyof OpenapiVerifyLogoutErrors];

export type OpenapiVerifyLogoutResponses = {
    /**
     * Authorized
     */
    200: OpenapiUtilsApiResponse____;
};

export type OpenapiVerifyLogoutResponse = OpenapiVerifyLogoutResponses[keyof OpenapiVerifyLogoutResponses];

export type OpenapiOtpAddData = {
    body: OpenapiOtpMobileAddRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/otp/add';
};

export type OpenapiOtpAddErrors = {
    /**
     * No valid session or failed
     */
    401: OpenapiOtpMobileResponse;
    /**
     * Per-recipient dispatch budget exhausted
     */
    429: OpenapiOtpMobileResponse;
};

export type OpenapiOtpAddError = OpenapiOtpAddErrors[keyof OpenapiOtpAddErrors];

export type OpenapiOtpAddResponses = {
    /**
     * Success — SMS code sent
     */
    200: OpenapiOtpMobileResponse;
};

export type OpenapiOtpAddResponse = OpenapiOtpAddResponses[keyof OpenapiOtpAddResponses];

export type OpenapiOtpAddVerifyData = {
    body: OpenapiOtpMobileAddVerifyRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/otp/add/verify';
};

export type OpenapiOtpAddVerifyErrors = {
    /**
     * No valid session, unknown/consumed token, wrong code, or the number was claimed in the meantime
     */
    401: OpenapiOtpMobileResponse;
};

export type OpenapiOtpAddVerifyError = OpenapiOtpAddVerifyErrors[keyof OpenapiOtpAddVerifyErrors];

export type OpenapiOtpAddVerifyResponses = {
    /**
     * Success — mobile attached to the session's account
     */
    200: OpenapiOtpMobileResponse;
};

export type OpenapiOtpAddVerifyResponse = OpenapiOtpAddVerifyResponses[keyof OpenapiOtpAddVerifyResponses];

export type OpenapiOtpRequestData = {
    body: OpenapiOtpReqRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/otp/request';
};

export type OpenapiOtpRequestErrors = {
    /**
     * Failed
     */
    401: OpenapiOtpMobileResponse;
    /**
     * Dispatch budget exhausted, or account locked after repeated verify failures
     */
    429: OpenapiOtpMobileResponse;
};

export type OpenapiOtpRequestError = OpenapiOtpRequestErrors[keyof OpenapiOtpRequestErrors];

export type OpenapiOtpRequestResponses = {
    /**
     * Success
     */
    200: OpenapiOtpMobileResponse;
};

export type OpenapiOtpRequestResponse = OpenapiOtpRequestResponses[keyof OpenapiOtpRequestResponses];

export type OpenapiOtpVerifyData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Unique token
         */
        token: string;
        /**
         * User name
         */
        name: string;
        /**
         * User mobile
         */
        mobile: string;
        /**
         * OTP code
         */
        code: string;
    };
    url: '/api/v1/auth/otp/verify';
};

export type OpenapiOtpVerifyErrors = {
    /**
     * Failed
     */
    401: OpenapiOtpMobileResponse;
    /**
     * Account locked after repeated verify failures
     */
    429: OpenapiOtpMobileResponse;
};

export type OpenapiOtpVerifyError = OpenapiOtpVerifyErrors[keyof OpenapiOtpVerifyErrors];

export type OpenapiOtpVerifyResponses = {
    /**
     * Success
     */
    200: OpenapiOtpMobileResponse;
};

export type OpenapiOtpVerifyResponse = OpenapiOtpVerifyResponses[keyof OpenapiOtpVerifyResponses];

export type OpenapiPasskeyRemoveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/passkey/remove';
};

export type OpenapiPasskeyRemoveErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type OpenapiPasskeyRemoveResponses = {
    /**
     * Passkeys deactivated
     */
    200: OpenapiUtilsApiResponse_String_;
};

export type OpenapiPasskeyRemoveResponse = OpenapiPasskeyRemoveResponses[keyof OpenapiPasskeyRemoveResponses];

export type OpenapiPasskeyRequestData = {
    body: OpenapiPasskeyPasskeyRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/passkey/request';
};

export type OpenapiPasskeyRequestErrors = {
    /**
     * Failed or no tenant found
     */
    401: unknown;
};

export type OpenapiPasskeyRequestResponses = {
    /**
     * Registration started successfully
     */
    200: OpenapiPasskeyPasskeyResponse;
};

export type OpenapiPasskeyRequestResponse = OpenapiPasskeyRequestResponses[keyof OpenapiPasskeyRequestResponses];

export type OpenapiPasskeyVerifyData = {
    body: OpenapiPasskeyVerifyRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/passkey/verify';
};

export type OpenapiPasskeyVerifyErrors = {
    /**
     * Verification failed or expired token
     */
    401: unknown;
};

export type OpenapiPasskeyVerifyResponses = {
    /**
     * Login successful
     */
    200: OpenapiUtilsApiResponse_String_;
};

export type OpenapiPasskeyVerifyResponse = OpenapiPasskeyVerifyResponses[keyof OpenapiPasskeyVerifyResponses];

export type OpenapiVerifyRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type OpenapiVerifyRefreshErrors = {
    /**
     * Unauthorized
     */
    401: OpenapiUtilsApiProblem;
};

export type OpenapiVerifyRefreshError = OpenapiVerifyRefreshErrors[keyof OpenapiVerifyRefreshErrors];

export type OpenapiVerifyRefreshResponses = {
    /**
     * Authorized
     */
    200: OpenapiUtilsApiResponse_String_;
};

export type OpenapiVerifyRefreshResponse = OpenapiVerifyRefreshResponses[keyof OpenapiVerifyRefreshResponses];

export type OpenapiVerifySessionInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/session';
};

export type OpenapiVerifySessionInfoErrors = {
    /**
     * No valid session
     */
    401: OpenapiUtilsApiProblem;
};

export type OpenapiVerifySessionInfoError = OpenapiVerifySessionInfoErrors[keyof OpenapiVerifySessionInfoErrors];

export type OpenapiVerifySessionInfoResponses = {
    /**
     * Session info
     */
    200: OpenapiUtilsApiResponse_openapiVerifySessionInfo_;
};

export type OpenapiVerifySessionInfoResponse = OpenapiVerifySessionInfoResponses[keyof OpenapiVerifySessionInfoResponses];

export type OpenapiSocialRedeemData = {
    body: OpenapiSocialRedeemRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/social/redeem';
};

export type OpenapiSocialRedeemErrors = {
    /**
     * Unknown, expired, or already-redeemed code
     */
    401: unknown;
};

export type OpenapiSocialRedeemResponses = {
    /**
     * ok — session JWT issued
     */
    200: unknown;
};

export type OpenapiSocialLinkData = {
    body?: never;
    path: {
        /**
         * Provider id, e.g. `github`
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/auth/social/{id}/link';
};

export type OpenapiSocialLinkErrors = {
    /**
     * No valid session
     */
    401: OpenapiUtilsApiProblem;
};

export type OpenapiSocialLinkError = OpenapiSocialLinkErrors[keyof OpenapiSocialLinkErrors];

export type OpenapiSocialLink2Data = {
    body?: never;
    path: {
        /**
         * Provider id, e.g. `github`
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/auth/social/{id}/link';
};

export type OpenapiSocialLink2Errors = {
    /**
     * No valid session
     */
    401: OpenapiUtilsApiProblem;
};

export type OpenapiSocialLink2Error = OpenapiSocialLink2Errors[keyof OpenapiSocialLink2Errors];

export type OpenapiSocialRequestData = {
    body?: never;
    path: {
        /**
         * Provider id, e.g. `github`
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/auth/social/{id}/request';
};

export type OpenapiSocialRequest2Data = {
    body?: never;
    path: {
        /**
         * Provider id, e.g. `github`
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/auth/social/{id}/request';
};

export type OpenapiSocialVerifyData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/auth/social/{id}/verify';
};

export type OpenapiSocialVerifyErrors = {
    /**
     * Missing code/state, invalid or expired state, or exchange/user failure
     */
    400: unknown;
    /**
     * State mismatch — possible CSRF attack
     */
    401: unknown;
};

export type OpenapiSocialVerify2Data = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/auth/social/{id}/verify';
};

export type OpenapiSocialVerify2Errors = {
    /**
     * Missing code/state, invalid or expired state, or exchange/user failure
     */
    400: unknown;
    /**
     * State mismatch — possible CSRF attack
     */
    401: unknown;
};

export type OpenapiTotpEnrollData = {
    body: OpenapiTotpEnrollTotpRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/totp/enroll';
};

export type OpenapiTotpEnrollErrors = {
    /**
     * Failed
     */
    401: OpenapiUtilsApiProblem;
    /**
     * Account locked after repeated verify failures
     */
    429: OpenapiUtilsApiProblem;
};

export type OpenapiTotpEnrollError = OpenapiTotpEnrollErrors[keyof OpenapiTotpEnrollErrors];

export type OpenapiTotpEnrollResponses = {
    /**
     * Success
     */
    200: OpenapiTotpEnrollTotpResponse;
};

export type OpenapiTotpEnrollResponse = OpenapiTotpEnrollResponses[keyof OpenapiTotpEnrollResponses];

export type OpenapiTotpEnroll2Data = {
    body: OpenapiTotpEnrollTotpRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/totp/enroll';
};

export type OpenapiTotpEnroll2Errors = {
    /**
     * Failed
     */
    401: OpenapiUtilsApiProblem;
    /**
     * Account locked after repeated verify failures
     */
    429: OpenapiUtilsApiProblem;
};

export type OpenapiTotpEnroll2Error = OpenapiTotpEnroll2Errors[keyof OpenapiTotpEnroll2Errors];

export type OpenapiTotpEnroll2Responses = {
    /**
     * Success
     */
    200: OpenapiTotpEnrollTotpResponse;
};

export type OpenapiTotpEnroll2Response = OpenapiTotpEnroll2Responses[keyof OpenapiTotpEnroll2Responses];

export type OpenapiTotpVerifyData = {
    body: OpenapiTotpVerifyTotpRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/totp/verify';
};

export type OpenapiTotpVerifyErrors = {
    /**
     * Failed
     */
    401: OpenapiUtilsApiProblem;
    /**
     * Account locked after repeated verify failures
     */
    429: OpenapiUtilsApiProblem;
};

export type OpenapiTotpVerifyError = OpenapiTotpVerifyErrors[keyof OpenapiTotpVerifyErrors];

export type OpenapiTotpVerifyResponses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse_String_;
};

export type OpenapiTotpVerifyResponse = OpenapiTotpVerifyResponses[keyof OpenapiTotpVerifyResponses];

export type OpenapiTotpVerify2Data = {
    body: OpenapiTotpVerifyTotpRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/totp/verify';
};

export type OpenapiTotpVerify2Errors = {
    /**
     * Failed
     */
    401: OpenapiUtilsApiProblem;
    /**
     * Account locked after repeated verify failures
     */
    429: OpenapiUtilsApiProblem;
};

export type OpenapiTotpVerify2Error = OpenapiTotpVerify2Errors[keyof OpenapiTotpVerify2Errors];

export type OpenapiTotpVerify2Responses = {
    /**
     * Success
     */
    200: OpenapiUtilsApiResponse_String_;
};

export type OpenapiTotpVerify2Response = OpenapiTotpVerify2Responses[keyof OpenapiTotpVerify2Responses];

export type OpenapiVerifyVerifyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/verify';
};

export type OpenapiVerifyVerifyErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type OpenapiVerifyVerifyResponses = {
    /**
     * Authorized
     */
    200: unknown;
};

export type OpenapiVerifyVerify2Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/verify';
};

export type OpenapiVerifyVerify2Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type OpenapiVerifyVerify2Responses = {
    /**
     * Authorized
     */
    200: unknown;
};

export type OpenapiOpsLiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/live';
};

export type OpenapiOpsLiveResponses = {
    /**
     * Process is alive
     */
    200: OpenapiOpsHealthyResponse;
};

export type OpenapiOpsLiveResponse = OpenapiOpsLiveResponses[keyof OpenapiOpsLiveResponses];

export type OpenapiOpsReadyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/ready';
};

export type OpenapiOpsReadyErrors = {
    /**
     * Not ready
     */
    503: OpenapiOpsHealthyResponse;
};

export type OpenapiOpsReadyError = OpenapiOpsReadyErrors[keyof OpenapiOpsReadyErrors];

export type OpenapiOpsReadyResponses = {
    /**
     * Ready to serve
     */
    200: OpenapiOpsHealthyResponse;
};

export type OpenapiOpsReadyResponse = OpenapiOpsReadyResponses[keyof OpenapiOpsReadyResponses];

export type OpenapiOpsHealthyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/healthy';
};

export type OpenapiOpsHealthyResponses = {
    /**
     * Server is up
     */
    200: OpenapiOpsHealthyResponse;
};

export type OpenapiOpsHealthyResponse2 = OpenapiOpsHealthyResponses[keyof OpenapiOpsHealthyResponses];
