#!/usr/bin/env python3
"""Render a Janux deploy pack from survey answers.

Copies examples/<layout>/ into --out, writes base.toml + seed.toml,
patches Caddyfile domain/path/TLS, and prints next steps.

Stdlib only. Safe defaults: generate-only, demo nginx backend, no secrets
on the command line required.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import secrets
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
EXAMPLES = REPO_ROOT / "examples"

SINGLE_SUBNET = "172.28.0.0/16"
SPLIT_SUBNET = "172.29.0.0/16"


def die(msg: str, code: int = 1) -> None:
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(code)


def load_answers(args: argparse.Namespace) -> dict:
    data: dict = {}
    if args.answers:
        path = Path(args.answers)
        if not path.is_file():
            die(f"answers file not found: {path}")
        data = json.loads(path.read_text())
        if not isinstance(data, dict):
            die("answers JSON must be an object")

    def pick(key: str, flag_val, default=None):
        if flag_val is not None:
            return flag_val
        if key in data and data[key] is not None:
            return data[key]
        return default

    layout = pick("layout", args.layout, "single-host")
    if layout not in ("single-host", "split-hosts"):
        die("layout must be single-host or split-hosts")

    domain = pick("domain", args.domain)
    if not domain:
        die("domain is required (flag or answers JSON)")

    app_domain = pick("app_domain", args.app_domain)
    if layout == "split-hosts" and not app_domain:
        die("split-hosts requires app_domain")

    resource = pick("resource", args.resource, "/app")
    if not str(resource).startswith("/"):
        resource = "/" + str(resource)

    role = pick("role", args.role, "user")
    admin_email = pick("admin_email", args.admin_email, "admin@example.com")
    tls = pick("tls", args.tls, "internal")
    if tls not in ("internal", "acme"):
        die("tls must be internal or acme")

    backend = pick("backend", args.backend, "app:80")
    trusted = pick(
        "trusted_proxies",
        args.trusted_proxies,
        SINGLE_SUBNET if layout == "single-host" else SPLIT_SUBNET,
    )
    image = pick("image", args.image, "ghcr.io/afmkt/janux:latest")
    resend_key = pick("resend_key", args.resend_key)
    resend_from = pick("resend_from", args.resend_from, f"no-reply@{domain}")
    encryption_key = pick("encryption_key", args.encryption_key)
    if not encryption_key:
        encryption_key = secrets.token_hex(32)

    verify_scheme = "https"
    verify_host = domain if layout == "single-host" else (app_domain or domain)
    verify_url = pick(
        "verify_url",
        args.verify_url,
        f"{verify_scheme}://{verify_host}/login",
    )

    tenant_name = pick("tenant_name", args.tenant_name, domain)

    return {
        "layout": layout,
        "domain": domain,
        "app_domain": app_domain,
        "resource": resource,
        "role": role,
        "admin_email": admin_email,
        "tls": tls,
        "backend": backend,
        "trusted_proxies": trusted,
        "image": image,
        "resend_key": resend_key,
        "resend_from": resend_from,
        "encryption_key": encryption_key,
        "verify_url": verify_url,
        "tenant_name": tenant_name,
        "mode": pick("mode", None, "generate"),
    }


def copy_example(layout: str, out: Path) -> None:
    src = EXAMPLES / layout
    if not src.is_dir():
        die(f"example layout missing: {src}")
    if out.exists():
        die(f"output directory already exists: {out} (refuse to overwrite)")
    shutil.copytree(
        src,
        out,
        ignore=shutil.ignore_patterns(
            "base.toml",
            "seed.toml",
            "__pycache__",
            "*.pyc",
        ),
    )


def write_base_toml(out: Path, a: dict) -> None:
    content = f"""# Generated by scripts/render-deploy.py — review before production use.
# Prefer JANUX__encryption_key env var in production instead of the file field.

data_dir = \"./data\"
encryption_key = \"{a['encryption_key']}\"
trust_forwarded_headers = true
trusted_proxies = [\"{a['trusted_proxies']}\"]
forward_auth_redirect = true

[bind]
address = \"0.0.0.0\"
port = 8080
"""
    (out / "base.toml").write_text(content)


def write_seed_toml(out: Path, a: dict) -> None:
    domain = a["domain"]
    if a["layout"] == "split-hosts":
        domains_line = (
            f'[{{ id = "{domain}", cors = ["tenant"] }}, '
            f'{{ id = "{a["app_domain"]}", cors = ["tenant"] }}]'
        )
        policy_domain = a["app_domain"]
    else:
        domains_line = f'[{{ id = "{domain}", cors = [] }}, {{ id = "0.0.0.0", cors = [] }}]'
        policy_domain = domain

    resend_block = ""
    if a["resend_key"]:
        resend_block = f"""
[seed.resend]
from = \"{a['resend_from']}\"
resend_key = \"{a['resend_key']}\"
verify_url = \"{a['verify_url']}\"
"""
    else:
        resend_block = f"""
# Uncomment and set resend_key to enable email magic-link:
# [seed.resend]
# from = \"{a['resend_from']}\"
# resend_key = \"re_...\"
# verify_url = \"{a['verify_url']}\"
"""

    content = f"""# Generated by scripts/render-deploy.py — review before production use.
# Do not commit real provider secrets.

[[seed]]
name = \"{a['tenant_name']}\"
domains = {domains_line}
roles = [\"root\", \"admin\", \"scim\", \"user\", \"guest\"]
users = [
  {{ name = \"admin\", roles = [\"admin\"], active = true, email = \"{a['admin_email']}\" }},
]
policies = [
  {{ domain = \"{policy_domain}\", resource = \"{a['resource']}\", role = \"{a['role']}\" }},
  {{ domain = \"{policy_domain}\", resource = \"{a['resource']}\", role = \"admin\" }},
]
{resend_block}
"""
    (out / "seed.toml").write_text(content)


def patch_caddyfile(out: Path, a: dict) -> None:
    path = out / "Caddyfile"
    if not path.is_file():
        return
    text = path.read_text()

    if a["tls"] == "acme":
        text = re.sub(r"(?m)^\s*tls internal\s*\n", "", text)

    resource = a["resource"]
    text = re.sub(r"path\s+/app\b", f"path {resource}", text)
    text = re.sub(r"@appName\b", "@gated", text)

    if a["layout"] == "single-host":
        text = re.sub(
            r"(?m)^localhost\s*\{",
            f"{a['domain']} {{",
            text,
            count=1,
        )
    else:
        if a["app_domain"]:
            text = text.replace("app.example.com", a["app_domain"])
        text = text.replace("auth.example.com", a["domain"])

    path.write_text(text)


def patch_compose(out: Path, a: dict) -> None:
    path = out / "compose.yml"
    if not path.is_file():
        return
    text = path.read_text()
    if a["image"] and "ghcr.io/afmkt/janux" in text:
        text = re.sub(
            r"image:\s*ghcr\.io/afmkt/janux:\S+",
            f"image: {a['image']}",
            text,
        )
    path.write_text(text)


def write_readme(out: Path, a: dict) -> None:
    domain = a["domain"] if a["layout"] == "single-host" else a["app_domain"]
    (out / "DEPLOY.md").write_text(
        f"""# Janux deploy pack

Generated by `scripts/render-deploy.py`.

| Field | Value |
|-------|-------|
| layout | {a['layout']} |
| domain | {a['domain']} |
| app_domain | {a.get('app_domain') or '—'} |
| resource | {a['resource']} |
| role | {a['role']} |
| tls | {a['tls']} |
| mode | {a['mode']} |

## Next steps

1. Review `seed.toml` (admin email, optional Resend/SMS keys).
2. Prefer injecting the encryption key via env in production:
   `JANUX__encryption_key=...` (key is also in `base.toml` for local runs).
3. Start:

```sh
cd {out.resolve()}
docker compose up -d
```

4. Wait until ready:

```sh
curl -fsS https://{domain}/api/v1/health/ready
```

5. Open `https://{domain}/login` and complete the admin magic link
   (requires a working mail provider in seed, or attach credentials later).

## Safety

- Do not commit this directory if it contains real secrets.
- `disable_rate_limits` must stay off on public hosts.
- Encryption key loss = data dir unrecoverable.
"""
    )


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Render a Janux deploy pack from survey answers.",
    )
    ap.add_argument("--answers", help="JSON file with survey answers")
    ap.add_argument("--out", required=True, help="Output directory (must not exist)")
    ap.add_argument("--layout", choices=("single-host", "split-hosts"))
    ap.add_argument("--domain")
    ap.add_argument("--app-domain")
    ap.add_argument("--resource", default=None)
    ap.add_argument("--role", default=None)
    ap.add_argument("--admin-email", default=None)
    ap.add_argument("--tls", choices=("internal", "acme"))
    ap.add_argument("--backend", default=None)
    ap.add_argument("--trusted-proxies", default=None)
    ap.add_argument("--image", default=None)
    ap.add_argument("--resend-key", default=None)
    ap.add_argument("--resend-from", default=None)
    ap.add_argument("--encryption-key", default=None)
    ap.add_argument("--verify-url", default=None)
    ap.add_argument("--tenant-name", default=None)
    args = ap.parse_args()

    a = load_answers(args)
    out = Path(args.out).resolve()

    copy_example(a["layout"], out)
    write_base_toml(out, a)
    write_seed_toml(out, a)
    patch_caddyfile(out, a)
    patch_compose(out, a)
    write_readme(out, a)

    for name in ("base.example.toml", "seed.example.toml"):
        p = out / name
        if p.exists():
            p.unlink()

    print(f"Wrote deploy pack → {out}")
    print(f"  layout={a['layout']} domain={a['domain']} resource={a['resource']}")
    print(f"  encryption_key is in base.toml (64 hex chars); back it up.")
    print()
    print("Next:")
    print(f"  1. Review {out / 'seed.toml'}")
    print(f"  2. cd {out} && docker compose up -d")
    host = a["domain"] if a["layout"] == "single-host" else a["app_domain"]
    print(f"  3. curl -fsS https://{host}/api/v1/health/ready")
    print(f"  4. Open https://{host}/login")
    if a["mode"] != "live":
        print()
        print("Generate-only mode: not starting containers. Hand pack to the user.")


if __name__ == "__main__":
    main()
